# Synthea CSV integration: complete walkthrough

This notebook exercises the complete CSV-only integration:

- configuration discovery before construction;
- every `Synthea` constructor argument;
- every public generator method;
- representative `synthea.properties` overrides;
- generation and loading through `SyntheaCSVDataset`; and
- an equivalence check against a direct Synthea Java invocation using the same version, parameters, configuration, and seeds.

The equivalence check asserts emitted CSV file names and ordered column names. Row counts, patient IDs, and byte hashes are reported as stronger diagnostics without being required to match across a published release binary and a fresh local source build.

## Prerequisites

Java 17 or newer, Git, and internet access must be available. PyHealth downloads and checksum-verifies its pinned Synthea JAR on first use unless `jar_path` is supplied. The reference path separately clones the official Synthea repository and builds/runs its release tag through Gradle, so the live cells can take several minutes.

In [10]:
import csv
import hashlib
import inspect
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path

from pyhealth.datasets import SyntheaCSVDataset
from pyhealth.models import Synthea

In [11]:
artifact_root = Path(".artifacts/synthea_csv").resolve()
artifact_root.mkdir(parents=True, exist_ok=True)
artifact_root

PosixPath('/home/soham/PyHealth/examples/.artifacts/synthea_csv')

## Public generator API

| Method | Purpose |
|---|---|
| `get_available_config()` | Return properties supported by the selected Synthea JAR |
| `output_path()` | Return the configured CSV directory |
| `resolved_output_path()` | Resolve a nested folder-per-run CSV directory when present |
| `with_config()` | Return a new generator with merged property overrides |
| `build_argv()` | Build the Java/Synthea argument vector without executing it |
| `run()` | Execute Synthea and validate that CSV output was produced |
| `ensure_generated()` | Reuse existing output or generate it when absent |

In [12]:
expected_public_methods = {
    "get_available_config",
    "output_path",
    "resolved_output_path",
    "with_config",
    "build_argv",
    "run",
    "ensure_generated",
}
assert all(hasattr(Synthea, name) for name in expected_public_methods)
{
    name: str(inspect.signature(getattr(Synthea, name)))
    for name in sorted(expected_public_methods)
}

{'build_argv': "(self, java: 'Path', jar: 'Path') -> 'list[str]'",
 'ensure_generated': "(self) -> 'Path'",
 'get_available_config': "(jar_path: 'str | Path | None' = None, auto_download: 'bool' = True, pattern: 'str' = '*') -> 'dict[str, str | None]'",
 'output_path': "(self) -> 'Path'",
 'resolved_output_path': "(self) -> 'Path'",
 'run': "(self) -> 'Path'",
 'with_config': "(self, config: 'Mapping[str, str | int | float | bool]') -> 'Synthea'"}

## 1. Discover supported Synthea configuration

These class methods work before a generator exists. `pattern` uses shell-style glob matching. Discovery reads `synthea.properties` from the actual pinned or explicitly supplied JAR, so it reflects the Synthea version that will run.

In [13]:
generation_properties = Synthea.get_available_config(
    pattern="generate.*"
)
list(sorted(generation_properties.items()))[:10]

[('generate.append_numbers_to_person_names', 'true'),
 ('generate.birthweights.default_file', 'birthweights.csv'),
 ('generate.birthweights.logging', 'false'),
 ('generate.costs.default_device_cost', '0.00'),
 ('generate.costs.default_encounter_cost', '125.00'),
 ('generate.costs.default_immunization_cost', '136.00'),
 ('generate.costs.default_lab_cost', '100.00'),
 ('generate.costs.default_medication_cost', '255.00'),
 ('generate.costs.default_procedure_cost', '500.00'),
 ('generate.costs.default_supply_cost', '0.00')]

The examples below use several ordinary Synthea properties:

- `generate.thread_pool_size=1` makes the equivalence run deterministic and serial;
- `generate.only_alive_patients=true` keeps only patients alive at the simulation end;
- `exporter.years_of_history=5` limits exported history;
- `exporter.csv.folder_per_run=false` keeps CSV files directly under the CSV directory; and
- `exporter.csv.append_mode=false` replaces rather than appends to prior CSV files.

CSV exporter selection itself is managed by the wrapper and should not be placed in `synthea_config`.

## 2. Construct a normal runnable generator

In [14]:
common_config = {
    "generate.thread_pool_size": 1,
    "generate.only_alive_patients": True,
    "exporter.years_of_history": 5,
    "exporter.csv.folder_per_run": False,
    "exporter.csv.append_mode": False,
}

generator = Synthea(
    output_dir=artifact_root / "generated",
    population=10,
    seed=42,
    clinician_seed=43,
    reference_date="20240101",
    gender="F",
    age_range="30-40",
    overflow_population=False,
    state="Massachusetts",
    city="Boston",
    synthea_config=common_config,
    timeout=900,
)
generator

Synthea(population=10, seed=42, state='Massachusetts', city='Boston', gender='F', age_range='30-40')

`output_path()` is the expected CSV location. `resolved_output_path()` initially returns the same path; if folder-per-run output is enabled, it locates the actual nested directory after generation. `build_argv()` is useful for inspection and testing and does not execute Java.

In [15]:
expected_csv_path = generator.output_path()
resolved_before_generation = generator.resolved_output_path()
preview_argv = generator.build_argv(Path("java"), Path("synthea.jar"))

print("Expected CSV path:", expected_csv_path)
print("Resolved path now:", resolved_before_generation)
print("Command preview:")
print(shlex.join(str(item) for item in preview_argv))

Expected CSV path: /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv
Resolved path now: /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv
Command preview:
java -jar synthea.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 42 -cs 43 -p 10 -r 20240101 -g F -a 30-40 -o false Massachusetts Boston

## 3. Update configuration without mutating the original

`with_config()` returns another generator, re-runs constructor validation, and recomputes derived state such as the fingerprinted generation directory.

In [16]:
updated_generator = generator.with_config({
    "generate.only_alive_patients": False,
    "exporter.years_of_history": 10,
})

assert generator.synthea_config["generate.only_alive_patients"] == "true"
assert updated_generator.synthea_config["generate.only_alive_patients"] == "false"
assert updated_generator.generation_dir != generator.generation_dir

{
    "original": generator.generation_dir,
    "updated": updated_generator.generation_dir,
}

{'original': PosixPath('/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4'),
 'updated': PosixPath('/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/69d4854b026bb54c817298b85df3947987f2d1c3921a4ea6c3e04631e2b863e2')}

## 4. Every constructor argument

The following generator is intentionally a **dry-run API example**. Snapshot, fixed-record, keep-matching, and custom-module inputs require domain-specific files, so this object is used only to prove argument coverage and inspect its command. Do not call `run()` on it until those placeholder files are replaced with valid Synthea inputs.

Passing `None` means that option is omitted and Synthea uses its own default. When both `local_config_path` and `synthea_config` define a property, the mapping is emitted later as a command-line override and therefore wins.

In [17]:
constructor_demo_root = artifact_root / "constructor_demo"
constructor_demo_root.mkdir(parents=True, exist_ok=True)
local_config_path = constructor_demo_root / "local.properties"
local_config_path.write_text(
    "generate.only_alive_patients = true\n"
    "exporter.years_of_history = 5\n",
    encoding="utf-8",
)

all_constructor_args = {
    "output_dir": constructor_demo_root / "output",
    "population": 25,
    "seed": 1001,
    "state": "Massachusetts",
    "city": "Boston",
    "clinician_seed": 1002,
    "single_person_seed": 1003,
    "reference_date": "20240101",
    "end_date": "20241231",
    "gender": "F",
    "age_range": "18-65",
    "overflow_population": False,
    "local_config_path": local_config_path,
    "local_modules_dir": constructor_demo_root / "modules",
    "initial_population_snapshot_path": constructor_demo_root / "initial.snapshot",
    "updated_population_snapshot_path": constructor_demo_root / "updated.snapshot",
    "update_time_period": 30,
    "fixed_record_path": constructor_demo_root / "fixed_records.json",
    "keep_matching_patients_path": constructor_demo_root / "keep_module.json",
    "java_path": None,
    "jar_path": None,
    "auto_download": True,
    "synthea_config": {
        "generate.thread_pool_size": 1,
        "generate.only_alive_patients": False,
        "exporter.csv.folder_per_run": False,
        "exporter.csv.append_mode": False,
    },
    "timeout": 900.0,
    "regenerate": False,
}

declared_args = set(inspect.signature(Synthea).parameters)
assert set(all_constructor_args) == declared_args
all_args_generator = Synthea(**all_constructor_args)
all_args_argv = all_args_generator.build_argv(Path("java"), Path("synthea.jar"))
assert all_args_argv.index("-c") < all_args_argv.index("--generate.only_alive_patients=false")
print(shlex.join(all_args_argv))

java -jar synthea.jar -c /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/local.properties --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/output/5edeeb5fa66bd2d663d3a052a9566c4eccb860b6ec5831c3ed16f6345c6f020a --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --generate.only_alive_patients=false --generate.thread_pool_size=1 -s 1001 -cs 1002 -ps 1003 -p 25 -r 20240101 -e 20241231 -g F -a 18-65 -o false -d /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/modules -i /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/initial.snapshot -u /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/updated.snapshot -t 30 -f /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/fixed_records.json -k /home/soham/PyHealth/examples/.artifacts/synthea_csv/constructor_demo/keep_module.json Massachusetts Boston

Constructor-to-CLI mapping:

| Python argument | Synthea CLI | Meaning |
|---|---|---|
| `seed` | `-s` | Population random seed |
| `clinician_seed` | `-cs` | Clinician generation seed |
| `single_person_seed` | `-ps` | Seed used to reproduce a particular person |
| `population` | `-p` | Requested population size |
| `reference_date` | `-r` | Reference date in `YYYYMMDD` form |
| `end_date` | `-e` | Simulation end date in `YYYYMMDD` form |
| `gender` | `-g` | Restrict generation to `M` or `F` |
| `age_range` | `-a` | Restrict age using `min-max` |
| `overflow_population` | `-o` | Permit extra generated people to satisfy filters |
| `local_config_path` | `-c` | Additional `.properties` configuration file |
| `local_modules_dir` | `-d` | Directory containing custom Synthea modules |
| `initial_population_snapshot_path` | `-i` | Load a previously saved population snapshot |
| `updated_population_snapshot_path` | `-u` | Write the population after an update run |
| `update_time_period` | `-t` | Number of days advanced during a snapshot update |
| `fixed_record_path` | `-f` | Fixed-demographics input used to generate specified people |
| `keep_matching_patients_path` | `-k` | Module used to retain only matching patients |
| `state`, `city` | trailing positional arguments | Geographic generation location |
| `synthea_config` | `--property=value` overrides | Arbitrary supported `synthea.properties` values |
| `output_dir` | wrapper-managed | Parent of the fingerprinted generation directory |
| `java_path` | wrapper-managed | Explicit Java executable, otherwise discovered |
| `jar_path` | wrapper-managed | Explicit Synthea JAR, otherwise the pinned release is used |
| `auto_download` | wrapper-managed | Allow downloading the pinned JAR when absent |
| `timeout` | wrapper-managed | Subprocess timeout in seconds |
| `regenerate` | wrapper-managed | Replace existing output on the first lazy access |

## 5. Generate, validate, and reuse CSV output

`run()` always executes Synthea. `ensure_generated()` is the cache check: it generates only when `patients.csv` is absent, unless `regenerate=True`, and returns the CSV directory either way.

In [18]:
csv_path = generator.run()
reused_path = generator.ensure_generated()
resolved_after_generation = generator.resolved_output_path()

assert csv_path == reused_path == resolved_after_generation
assert (csv_path / "patients.csv").is_file()
sorted(path.name for path in csv_path.glob("*.csv"))

Running Synthea: /home/soham/.local/jvm/jdk-17.0.20.1+1/bin/java -jar /home/soham/.cache/pyhealth/synthea/synthea-with-dependencies-v4.0.0.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 42 -cs 43 -p 10 -r 20240101 -g F -a 30-40 -o false Massachusetts Boston

org.mitre.synthea.X12.ExporterAdaptor
org.mitre.synthea.X12.ExporterAdaptor

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

Scanned 92 modules and 449 submodules.
Loading submodule modules/allergies/allergy_panel.json
Loading submodule modules/allergies/drug_allergy_incidence.json
Loading submodule modules/allergies/environmental_allergy_incidence.json
Loading submodule modules/allergies/food_allergy_incidence.json
Loading submodule modules/allergies/immunotherapy.json
Loading submodule modules/allergies/outgrow_env_allergies.json
Loading submodule modules/allergies/outgrow_food_allergies.json
Loading submodule modules/allergies/severe_allergic_reaction.json
Loading submodule modules/anemia/anemia_sub.json
Loading submodule modules/breast_cancer/chemotherapy_breast.json
Loading submodule modules/breast_cancer/hormone_diagnosis.json
Loading submodule modules/breast_cancer/hormonetherapy_breast.json
Loading submodule modules/breast_cancer/surgery_therapy_breast.json
Loading submodule modules/breast_cancer/tnm_diagnosis.json
Loading submodule modules/contraceptives/clear_contraceptive.json
Loading submodule modules/contraceptives/female_sterilization.json
Loading submodule modules/contraceptives/implant_contraceptive.json
Loading submodule modules/contraceptives/injectable_contraceptive.json
Loading submodule modules/contraceptives/intrauterine_device.json
Loading submodule modules/contraceptives/male_sterilization.json
Loading submodule modules/contraceptives/oral_contraceptive.json
Loading submodule modules/contraceptives/patch_contraceptive.json
Loading submodule modules/contraceptives/ring_contraceptive.json
Loading submodule modules/covid19/admission.json
Loading submodule modules/covid19/determine_risk.json
Loading Lookup Table: covid-19-severity-outcomes.csv
Loading Lookup Table: covid-19-survival-outcomes.csv
Loading submodule modules/covid19/diagnose_bacterial_infection.json
Loading submodule modules/covid19/diagnose_blood_clot.json
Loading submodule modules/covid19/end_outcomes.json
Loading submodule modules/covid19/end_symptoms.json
Loading submodule modules/covid19/infection.json
Loading submodule modules/covid19/measurements_daily.json
Loading submodule modules/covid19/measurements_frequent.json
Loading submodule modules/covid19/measurements_vitals.json
Loading submodule modules/covid19/medications.json
Loading submodule modules/covid19/nonsurvivor_lab_values.json
Loading submodule modules/covid19/outcomes.json
Loading submodule modules/covid19/supplies_hospitalization.json
Loading submodule modules/covid19/supplies_icu.json
Loading submodule modules/covid19/supplies_intubation.json
Loading submodule modules/covid19/survivor_lab_values.json
Loading submodule modules/covid19/symptoms.json
Loading submodule modules/covid19/treat_blood_clot.json
Loading submodule modules/dental/dental_emergency.json
Loading submodule modules/dental/dental_encounter.json
Loading submodule modules/dental/dental_hospital.json
Loading submodule modules/dental/dental_telephone.json
Loading submodule modules/dental/diagnosis/cavity.json
Loading submodule modules/dental/diagnosis/dental disorder.json
Loading submodule modules/dental/diagnosis/gingivitis.json
Loading submodule modules/dental/diagnosis/periodontitis.json
Loading submodule modules/dental/diagnosis/plaque.json
Loading submodule modules/dental/end_dental_diagnoses.json
Loading submodule modules/dental/procedure/d01.json
Loading submodule modules/dental/procedure/d02.json
Loading submodule modules/dental/procedure/d03.json
Loading submodule modules/dental/procedure/d04.json
Loading submodule modules/dental/procedure/d05.json
Loading submodule modules/dental/procedure/d06.json
Loading submodule modules/dental/procedure/d09.json
Loading submodule modules/dental/procedure/d11.json
Loading submodule modules/dental/procedure/d12.json
Loading submodule modules/dental/procedure/d13.json
Loading submodule modules/dental/procedure/d15.json
Loading submodule modules/dental/procedure/d19.json
Loading submodule modules/dental/procedure/d21.json
Loading submodule modules/dental/procedure/d23.json
Loading submodule modules/dental/procedure/d25.json
Loading submodule modules/dental/procedure/d26.json
Loading submodule modules/dental/procedure/d27.json
Loading submodule modules/dental/procedure/d29.json
Loading submodule modules/dental/procedure/d31.json
Loading submodule modules/dental/procedure/d32.json
Loading submodule modules/dental/procedure/d33.json
Loading submodule modules/dental/procedure/d34.json
Loading submodule modules/dental/procedure/d39.json
Loading submodule modules/dental/procedure/d42.json
Loading submodule modules/dental/procedure/d43.json
Loading submodule modules/dental/procedure/d49.json
Loading submodule modules/dental/procedure/d51.json
Loading submodule modules/dental/procedure/d52.json
Loading submodule modules/dental/procedure/d54.json
Loading submodule modules/dental/procedure/d55.json
Loading submodule modules/dental/procedure/d56.json
Loading submodule modules/dental/procedure/d57.json
Loading submodule modules/dental/procedure/d58.json
Loading submodule modules/dental/procedure/d59.json
Loading submodule modules/dental/procedure/d60.json
Loading submodule modules/dental/procedure/d61.json
Loading submodule modules/dental/procedure/d62.json
Loading submodule modules/dental/procedure/d65.json
Loading submodule modules/dental/procedure/d66.json
Loading submodule modules/dental/procedure/d67.json
Loading submodule modules/dental/procedure/d69.json
Loading submodule modules/dental/procedure/d71.json
Loading submodule modules/dental/procedure/d72.json
Loading submodule modules/dental/procedure/d73.json
Loading submodule modules/dental/procedure/d74.json
Loading submodule modules/dental/procedure/d75.json
Loading submodule modules/dental/procedure/d76.json
Loading submodule modules/dental/procedure/d77.json
Loading submodule modules/dental/procedure/d78.json
Loading submodule modules/dental/procedure/d79.json
Loading submodule modules/dental/procedure/d80.json
Loading submodule modules/dental/procedure/d82.json
Loading submodule modules/dental/procedure/d86.json
Loading submodule modules/dental/procedure/d89.json
Loading submodule modules/dental/procedure/d91.json
Loading submodule modules/dental/procedure/d92.json
Loading submodule modules/dental/procedure/d93.json
Loading submodule modules/dental/procedure/d94.json
Loading submodule modules/dental/procedure/d96.json
Loading submodule modules/dental/procedure/d99.json
Loading submodule modules/dental_idr/dental_idr_cluster_0.json
Loading submodule modules/dental_idr/dental_idr_cluster_1.json
Loading submodule modules/dental_idr/dental_idr_cluster_2.json
Loading submodule modules/dental_idr/dental_idr_cluster_3.json
Loading submodule modules/dental_idr/dental_idr_cluster_4.json
Loading submodule modules/dental_idr/diagnosis/c00.json
Loading submodule modules/dental_idr/diagnosis/c01.json
Loading submodule modules/dental_idr/diagnosis/c02.json
Loading submodule modules/dental_idr/diagnosis/c03.json
Loading submodule modules/dental_idr/diagnosis/c04.json
Loading submodule modules/dental_idr/diagnosis/c05.json
Loading submodule modules/dental_idr/diagnosis/c06.json
Loading submodule modules/dental_idr/diagnosis/c07.json
Loading submodule modules/dental_idr/diagnosis/c08.json
Loading submodule modules/dental_idr/diagnosis/c09.json
Loading submodule modules/dental_idr/diagnosis/c10.json
Loading submodule modules/dental_idr/diagnosis/c11.json
Loading submodule modules/dental_idr/diagnosis/c12.json
Loading submodule modules/dental_idr/diagnosis/c13.json
Loading submodule modules/dental_idr/diagnosis/c14.json
Loading submodule modules/dental_idr/diagnosis/c15.json
Loading submodule modules/dental_idr/diagnosis/c16.json
Loading submodule modules/dental_idr/diagnosis/c17.json
Loading submodule modules/dental_idr/diagnosis/c18.json
Loading submodule modules/dental_idr/diagnosis/c19.json
Loading submodule modules/dental_idr/diagnosis/c20.json
Loading submodule modules/dental_idr/diagnosis/c21.json
Loading submodule modules/dental_idr/diagnosis/c22.json
Loading submodule modules/dental_idr/diagnosis/c24.json
Loading submodule modules/dental_idr/diagnosis/c25.json
Loading submodule modules/dental_idr/diagnosis/c26.json
Loading submodule modules/dental_idr/diagnosis/c30.json
Loading submodule modules/dental_idr/diagnosis/c31.json
Loading submodule modules/dental_idr/diagnosis/c32.json
Loading submodule modules/dental_idr/diagnosis/c33.json
Loading submodule modules/dental_idr/diagnosis/c34.json
Loading submodule modules/dental_idr/diagnosis/c37.json
Loading submodule modules/dental_idr/diagnosis/c38.json
Loading submodule modules/dental_idr/diagnosis/c39.json
Loading submodule modules/dental_idr/diagnosis/c40.json
Loading submodule modules/dental_idr/diagnosis/c41.json
Loading submodule modules/dental_idr/diagnosis/c43.json
Loading submodule modules/dental_idr/diagnosis/c44.json
Loading submodule modules/dental_idr/diagnosis/c45.json
Loading submodule modules/dental_idr/diagnosis/c46.json
Loading submodule modules/dental_idr/diagnosis/c47.json
Loading submodule modules/dental_idr/diagnosis/c48.json
Loading submodule modules/dental_idr/diagnosis/c49.json
Loading submodule modules/dental_idr/diagnosis/c4a.json
Loading submodule modules/dental_idr/diagnosis/c50.json
Loading submodule modules/dental_idr/diagnosis/c51.json
Loading submodule modules/dental_idr/diagnosis/c53.json
Loading submodule modules/dental_idr/diagnosis/c54.json
Loading submodule modules/dental_idr/diagnosis/c56.json
Loading submodule modules/dental_idr/diagnosis/c57.json
Loading submodule modules/dental_idr/diagnosis/c61.json
Loading submodule modules/dental_idr/diagnosis/c62.json
Loading submodule modules/dental_idr/diagnosis/c63.json
Loading submodule modules/dental_idr/diagnosis/c64.json
Loading submodule modules/dental_idr/diagnosis/c65.json
Loading submodule modules/dental_idr/diagnosis/c66.json
Loading submodule modules/dental_idr/diagnosis/c67.json
Loading submodule modules/dental_idr/diagnosis/c68.json
Loading submodule modules/dental_idr/diagnosis/c69.json
Loading submodule modules/dental_idr/diagnosis/c71.json
Loading submodule modules/dental_idr/diagnosis/c72.json
Loading submodule modules/dental_idr/diagnosis/c73.json
Loading submodule modules/dental_idr/diagnosis/c74.json
Loading submodule modules/dental_idr/diagnosis/c75.json
Loading submodule modules/dental_idr/diagnosis/c76.json
Loading submodule modules/dental_idr/diagnosis/c77.json
Loading submodule modules/dental_idr/diagnosis/c78.json
Loading submodule modules/dental_idr/diagnosis/c79.json
Loading submodule modules/dental_idr/diagnosis/c7a.json
Loading submodule modules/dental_idr/diagnosis/c7b.json
Loading submodule modules/dental_idr/diagnosis/c80.json
Loading submodule modules/dental_idr/diagnosis/c81.json
Loading submodule modules/dental_idr/diagnosis/c82.json
Loading submodule modules/dental_idr/diagnosis/c83.json
Loading submodule modules/dental_idr/diagnosis/c84.json
Loading submodule modules/dental_idr/diagnosis/c85.json
Loading submodule modules/dental_idr/diagnosis/c86.json
Loading submodule modules/dental_idr/diagnosis/c88.json
Loading submodule modules/dental_idr/diagnosis/c90.json
Loading submodule modules/dental_idr/diagnosis/c91.json
Loading submodule modules/dental_idr/diagnosis/c92.json
Loading submodule modules/dental_idr/diagnosis/c93.json
Loading submodule modules/dental_idr/diagnosis/c95.json
Loading submodule modules/dental_idr/diagnosis/c96.json
Loading submodule modules/dental_idr/diagnosis/d00.json
Loading submodule modules/dental_idr/diagnosis/d01.json
Loading submodule modules/dental_idr/diagnosis/d02.json
Loading submodule modules/dental_idr/diagnosis/d03.json
Loading submodule modules/dental_idr/diagnosis/d04.json
Loading submodule modules/dental_idr/diagnosis/d05.json
Loading submodule modules/dental_idr/diagnosis/d06.json
Loading submodule modules/dental_idr/diagnosis/d07.json
Loading submodule modules/dental_idr/diagnosis/d09.json
Loading submodule modules/dental_idr/diagnosis/d10.json
Loading submodule modules/dental_idr/diagnosis/d11.json
Loading submodule modules/dental_idr/diagnosis/d12.json
Loading submodule modules/dental_idr/diagnosis/d13.json
Loading submodule modules/dental_idr/diagnosis/d14.json
Loading submodule modules/dental_idr/diagnosis/d16.json
Loading submodule modules/dental_idr/diagnosis/d17.json
Loading submodule modules/dental_idr/diagnosis/d18.json
Loading submodule modules/dental_idr/diagnosis/d19.json
Loading submodule modules/dental_idr/diagnosis/d21.json
Loading submodule modules/dental_idr/diagnosis/d22.json
Loading submodule modules/dental_idr/diagnosis/d23.json
Loading submodule modules/dental_idr/diagnosis/d24.json
Loading submodule modules/dental_idr/diagnosis/d25.json
Loading submodule modules/dental_idr/diagnosis/d28.json
Loading submodule modules/dental_idr/diagnosis/d29.json
Loading submodule modules/dental_idr/diagnosis/d30.json
Loading submodule modules/dental_idr/diagnosis/d31.json
Loading submodule modules/dental_idr/diagnosis/d32.json
Loading submodule modules/dental_idr/diagnosis/d33.json
Loading submodule modules/dental_idr/diagnosis/d34.json
Loading submodule modules/dental_idr/diagnosis/d35.json
Loading submodule modules/dental_idr/diagnosis/d36.json
Loading submodule modules/dental_idr/diagnosis/d37.json
Loading submodule modules/dental_idr/diagnosis/d38.json
Loading submodule modules/dental_idr/diagnosis/d39.json
Loading submodule modules/dental_idr/diagnosis/d3a.json
Loading submodule modules/dental_idr/diagnosis/d40.json
Loading submodule modules/dental_idr/diagnosis/d41.json
Loading submodule modules/dental_idr/diagnosis/d44.json
Loading submodule modules/dental_idr/diagnosis/d45.json
Loading submodule modules/dental_idr/diagnosis/d46.json
Loading submodule modules/dental_idr/diagnosis/d47.json
Loading submodule modules/dental_idr/diagnosis/d48.json
Loading submodule modules/dental_idr/diagnosis/d49.json
Loading submodule modules/dental_idr/diagnosis/k00.json
Loading submodule modules/dental_idr/diagnosis/k01.json
Loading submodule modules/dental_idr/diagnosis/k02.json
Loading submodule modules/dental_idr/diagnosis/k03.json
Loading submodule modules/dental_idr/diagnosis/k04.json
Loading submodule modules/dental_idr/diagnosis/k05.json
Loading submodule modules/dental_idr/diagnosis/k06.json
Loading submodule modules/dental_idr/diagnosis/k08.json
Loading submodule modules/dental_idr/diagnosis/k09.json
Loading submodule modules/dental_idr/diagnosis/k11.json
Loading submodule modules/dental_idr/diagnosis/k12.json
Loading submodule modules/dental_idr/diagnosis/k13.json
Loading submodule modules/dental_idr/diagnosis/m26.json
Loading submodule modules/dental_idr/diagnosis/m27.json
Loading submodule modules/dental_idr/diagnosis/r69.json
Loading submodule modules/dental_idr/diagnosis/s02.json
Loading submodule modules/dental_idr/diagnosis/z00.json
Loading submodule modules/dental_idr/diagnosis/z01.json
Loading submodule modules/dental_idr/diagnosis/z13.json
Loading submodule modules/dental_idr/diagnosis/z40.json
Loading submodule modules/dental_idr/diagnosis/z41.json
Loading submodule modules/dental_idr/diagnosis/z51.json
Loading submodule modules/dental_idr/end_dental_diagnoses.json
Loading submodule modules/dental_idr/procedure/d01.json
Loading submodule modules/dental_idr/procedure/d02.json
Loading submodule modules/dental_idr/procedure/d03.json
Loading submodule modules/dental_idr/procedure/d04.json
Loading submodule modules/dental_idr/procedure/d05.json
Loading submodule modules/dental_idr/procedure/d06.json
Loading submodule modules/dental_idr/procedure/d07.json
Loading submodule modules/dental_idr/procedure/d08.json
Loading submodule modules/dental_idr/procedure/d09.json
Loading submodule modules/dental_idr/procedure/d11.json
Loading submodule modules/dental_idr/procedure/d12.json
Loading submodule modules/dental_idr/procedure/d13.json
Loading submodule modules/dental_idr/procedure/d15.json
Loading submodule modules/dental_idr/procedure/d17.json
Loading submodule modules/dental_idr/procedure/d19.json
Loading submodule modules/dental_idr/procedure/d21.json
Loading submodule modules/dental_idr/procedure/d23.json
Loading submodule modules/dental_idr/procedure/d24.json
Loading submodule modules/dental_idr/procedure/d25.json
Loading submodule modules/dental_idr/procedure/d26.json
Loading submodule modules/dental_idr/procedure/d27.json
Loading submodule modules/dental_idr/procedure/d29.json
Loading submodule modules/dental_idr/procedure/d31.json
Loading submodule modules/dental_idr/procedure/d32.json
Loading submodule modules/dental_idr/procedure/d33.json
Loading submodule modules/dental_idr/procedure/d34.json
Loading submodule modules/dental_idr/procedure/d35.json
Loading submodule modules/dental_idr/procedure/d39.json
Loading submodule modules/dental_idr/procedure/d42.json
Loading submodule modules/dental_idr/procedure/d43.json
Loading submodule modules/dental_idr/procedure/d49.json
Loading submodule modules/dental_idr/procedure/d51.json
Loading submodule modules/dental_idr/procedure/d52.json
Loading submodule modules/dental_idr/procedure/d54.json
Loading submodule modules/dental_idr/procedure/d55.json
Loading submodule modules/dental_idr/procedure/d56.json
Loading submodule modules/dental_idr/procedure/d57.json
Loading submodule modules/dental_idr/procedure/d58.json
Loading submodule modules/dental_idr/procedure/d59.json
Loading submodule modules/dental_idr/procedure/d60.json
Loading submodule modules/dental_idr/procedure/d61.json
Loading submodule modules/dental_idr/procedure/d62.json
Loading submodule modules/dental_idr/procedure/d65.json
Loading submodule modules/dental_idr/procedure/d66.json
Loading submodule modules/dental_idr/procedure/d67.json
Loading submodule modules/dental_idr/procedure/d69.json
Loading submodule modules/dental_idr/procedure/d71.json
Loading submodule modules/dental_idr/procedure/d72.json
Loading submodule modules/dental_idr/procedure/d73.json
Loading submodule modules/dental_idr/procedure/d74.json
Loading submodule modules/dental_idr/procedure/d75.json
Loading submodule modules/dental_idr/procedure/d76.json
Loading submodule modules/dental_idr/procedure/d77.json
Loading submodule modules/dental_idr/procedure/d78.json
Loading submodule modules/dental_idr/procedure/d79.json
Loading submodule modules/dental_idr/procedure/d80.json
Loading submodule modules/dental_idr/procedure/d82.json
Loading submodule modules/dental_idr/procedure/d86.json
Loading submodule modules/dental_idr/procedure/d87.json
Loading submodule modules/dental_idr/procedure/d89.json
Loading submodule modules/dental_idr/procedure/d91.json
Loading submodule modules/dental_idr/procedure/d92.json
Loading submodule modules/dental_idr/procedure/d93.json
Loading submodule modules/dental_idr/procedure/d94.json
Loading submodule modules/dental_idr/procedure/d96.json
Loading submodule modules/dental_idr/procedure/d99.json
Loading submodule modules/dermatitis/early_moderate_eczema_obs.json
Loading submodule modules/dermatitis/early_severe_eczema_obs.json
Loading submodule modules/dermatitis/mid_moderate_eczema_obs.json
Loading submodule modules/dermatitis/mid_severe_eczema_obs.json
Loading submodule modules/dermatitis/moderate_cd_obs.json
Loading submodule modules/dermatitis/severe_cd_obs.json
Loading submodule modules/dme/wheelchair.json
Loading submodule modules/dme/wheelchair_end.json
Loading submodule modules/encounter/anxiety_screening.json
Loading submodule modules/encounter/depression_screening.json
Loading submodule modules/encounter/fall_risk_screening.json
Loading submodule modules/encounter/hark_screening.json
Loading submodule modules/encounter/hospital_basic_labs.json
Loading submodule modules/encounter/sdoh_hrsn.json
Loading submodule modules/encounter/substance_use_screening.json
Loading submodule modules/encounter/vitals.json
Loading submodule modules/eye/intraocular_pressure.json
Loading submodule modules/eye/ophthalmic_progression.json
Loading submodule modules/eye/ophthalmic_tomography.json

['allergies.csv',
 'careplans.csv',
 'claims.csv',
 'claims_transactions.csv',
 'conditions.csv',
 'devices.csv',
 'encounters.csv',
 'imaging_studies.csv',
 'immunizations.csv',
 'medications.csv',
 'observations.csv',
 'organizations.csv',
 'patients.csv',
 'payer_transitions.csv',
 'payers.csv',
 'procedures.csv',
 'providers.csv',
 'supplies.csv']

## 6. Load generated CSV through PyHealth

`SyntheaCSVDataset` only reads files: it takes the CSV directory returned by `run()` or `ensure_generated()` plus an optional table selection. Omitting `tables` uses all supported defaults. `dataset_name`, `config_path`, and normal `BaseDataset` keyword arguments such as `cache_dir` and `dev` can also be supplied.

In [19]:
dataset = SyntheaCSVDataset(
    root=csv_path,
    tables=["patients", "encounters", "conditions", "observations"],
    dataset_name="synthea_csv_demo",
    config_path=None,
    cache_dir=artifact_root / "cache",
    dev=False,
)

events = dataset.load_data()
dataset.stats()
# events.head(5)
events

Initializing synthea_csv_demo dataset from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv (dev mode: False)
Using provided cache_dir: /home/soham/PyHealth/examples/.artifacts/synthea_csv/cache/52ec6deb-b3eb-515b-a2e3-c799d1d15b9a
Scanning table: patients from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv/patients.csv
Scanning table: encounters from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv/encounters.csv
Scanning table: conditions from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv/conditions.csv
Scanning table: observations from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv/observations.csv
Found cached event dataframe: /home/soham/PyHealth/examples/.artifacts/synthea_csv/cache/52ec6deb-b3eb-515b-a2e3-c799d1d15b9a/global_event_df.parquet
Dataset: synthea_csv_demo
Dev mode: False
Number of patients: 10
Number of events: 2779

Dask DataFrame Structure:
              patient_id event_type       timestamp patients/birthdate patients/deathdate patients/gender patients/race patients/ethnicity patients/marital patients/birthplace patients/city patients/state patients/county patients/zip encounters/id encounters/start encounters/stop encounters/encounterclass encounters/code encounters/description encounters/base_encounter_cost encounters/total_claim_cost encounters/payer_coverage encounters/reasoncode encounters/reasondescription conditions/start conditions/stop conditions/encounter conditions/code conditions/description observations/date observations/encounter observations/code observations/description observations/value observations/units observations/type
npartitions=4
                  string     object  datetime64[ms]             string             string          string        string             string           string              string        string         string          string       string        string           string          string                    string          string                 string                         string                      string                    string                string                       string           string          string               string          string                 string            string                 string            string                   string             string             string            string
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
Dask Name: concat, 57 expressions
Expr=Concat(frames=[(RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(88abdc9), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'birthdate': 'patients/birthdate', 'deathdate': 'patients/deathdate', 'gender': 'patients/gender', 'race': 'patients/race', 'ethnicity': 'patients/ethnicity', 'marital': 'patients/marital', 'birthplace': 'patients/birthplace', 'city': 'patients/city', 'state': 'patients/state', 'county': 'patients/county', 'zip': 'patients/zip'}))[['patient_id', 'event_type', 'timestamp', 'patients/birthdate', 'patients/deathdate', 'patients/gender', 'patients/race', 'patients/ethnicity', 'patients/marital', 'patients/birthplace', 'patients/city', 'patients/state', 'patients/county', 'patients/zip']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(8fc9a65), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'id': 'encounters/id', 'start': 'encounters/start', 'stop': 'encounters/stop', 'encounterclass': 'encounters/encounterclass', 'code': 'encounters/code', 'description': 'encounters/description', 'base_encounter_cost': 'encounters/base_encounter_cost', 'total_claim_cost': 'encounters/total_claim_cost', 'payer_coverage': 'encounters/payer_coverage', 'reasoncode': 'encounters/reasoncode', 'reasondescription': 'encounters/reasondescription'}))[['patient_id', 'event_type', 'timestamp', 'encounters/id', 'encounters/start', 'encounters/stop', 'encounters/encounterclass', 'encounters/code', 'encounters/description', 'encounters/base_encounter_cost', 'encounters/total_claim_cost', 'encounters/payer_coverage', 'encounters/reasoncode', 'encounters/reasondescription']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(5007874), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'start': 'conditions/start', 'stop': 'conditions/stop', 'encounter': 'conditions/encounter', 'code': 'conditions/code', 'description': 'conditions/description'}))[['patient_id', 'event_type', 'timestamp', 'conditions/start', 'conditions/stop', 'conditions/encounter', 'conditions/code', 'conditions/description']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(6fa5c5b), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'date': 'observations/date', 'encounter': 'observations/encounter', 'code': 'observations/code', 'description': 'observations/description', 'value': 'observations/value', 'units': 'observations/units', 'type': 'observations/type'}))[['patient_id', 'event_type', 'timestamp', 'observations/date', 'observations/encounter', 'observations/code', 'observations/description', 'observations/value', 'observations/units', 'observations/type']]], )

In [20]:
patients_table = dataset.load_table("patients")
patient_ids = dataset.unique_patient_ids
patient = dataset.get_patient(patient_ids[0])
patient_events = patient.get_events(return_df=True)

print("Patients:", len(patient_ids))
print("Selected patient:", patient.patient_id)
print("Configured tables:", dataset.tables)
patient_events.head(10)

Scanning table: patients from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/999ea78e6ea632557cee855051132f901a3b9eca55bc4c349bbaffd06ba355d4/csv/patients.csv
Found 10 unique patient IDs
Patients: 10
Selected patient: 76b20010-c318-5754-8c85-983aa538522f
Configured tables: ['patients', 'encounters', 'conditions', 'observations']

shape: (10, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ patient_i ┆ event_typ ┆ timestamp ┆ patients/ ┆ … ┆ observati ┆ observati ┆ observati ┆ observat │
│ d         ┆ e         ┆ ---       ┆ birthdate ┆   ┆ ons/descr ┆ ons/value ┆ ons/units ┆ ions/typ │
│ ---       ┆ ---       ┆ datetime[ ┆ ---       ┆   ┆ iption    ┆ ---       ┆ ---       ┆ e        │
│ str       ┆ str       ┆ ms]       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 76b20010- ┆ patients  ┆ 1992-09-1 ┆ 1992-09-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆           ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ encounter ┆ 2007-11-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 01:52:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ condition ┆ 2008-02-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ condition ┆ 2010-11-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ encounter ┆ 2010-11-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 01:52:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ condition ┆ 2011-11-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ encounter ┆ 2011-11-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 01:52:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ condition ┆ 2015-12-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ encounter ┆ 2015-12-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 01:52:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 76b20010- ┆ condition ┆ 2020-11-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ c318-5754 ┆ s         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8c85-983 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ aa5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘