# Synthea CSV integration: complete walkthrough

**Prerequisite:** Java 17+ must be installed (on `PATH`, via `JAVA_HOME`, or passed as `java_path=`). PyHealth does not install it. You do not need to download Synthea itself: the pinned JAR is downloaded and checksum-verified on the first `generate()` call. See the *Setup* section of the `pyhealth.models.Synthea` API docs for Java install commands and offline use.

This notebook walks through the CSV integration:

- discovering supported `synthea.properties` before generating anything;
- setting up one `Synthea` generator and previewing its command;
- generating several populations from that one instance, with reuse and `overwrite`;
- every `generate()` argument and the Synthea CLI flag it maps to;
- loading generated CSV through `SyntheaCSVDataset`; and
- how Synthea data differs from other PyHealth datasets.

## Prerequisites

Java 17 or newer and, on first use, internet access to download the pinned Synthea JAR (about 200 MB) unless `jar_path` is supplied. Each live generation below takes roughly 15 seconds for a handful of patients.

In [1]:
import inspect
import shlex
from pathlib import Path

from pyhealth.datasets import SyntheaCSVDataset
from pyhealth.models import Synthea

In [2]:
artifact_root = Path(".artifacts/synthea_csv").resolve()
artifact_root.mkdir(parents=True, exist_ok=True)
artifact_root

PosixPath('/home/soham/PyHealth/examples/.artifacts/synthea_csv')

## Public generator API

| Member | Purpose |
|---|---|
| `Synthea(output_dir, ...)` | Set up the generator: output location, Java and JAR discovery, timeout. Generates nothing. |
| `generate(...)` | Generate a population from per-call settings and return its CSV directory; reuses existing output for identical settings unless `overwrite=True` |
| `build_argv(java, jar, ...)` | Build the Java/Synthea command for given settings without running it |
| `get_available_config()` | Return properties supported by the selected Synthea JAR |

In [3]:
{
    "Synthea": str(inspect.signature(Synthea)),
    "generate": str(inspect.signature(Synthea.generate)),
    "build_argv": str(inspect.signature(Synthea.build_argv)),
    "get_available_config": str(inspect.signature(Synthea.get_available_config)),
}

{'Synthea': "(output_dir: 'str | Path', java_path: 'str | Path | None' = None, jar_path: 'str | Path | None' = None, auto_download: 'bool' = True, timeout: 'float | None' = None) -> 'None'",
 'generate': "(self, population: 'int | None' = None, seed: 'int | None' = None, state: 'str | None' = None, city: 'str | None' = None, clinician_seed: 'int | None' = None, single_person_seed: 'int | None' = None, reference_date: 'str | None' = None, end_date: 'str | None' = None, gender: 'str | None' = None, age_range: 'str | None' = None, overflow_population: 'bool | None' = None, local_config_path: 'str | Path | None' = None, local_modules_dir: 'str | Path | None' = None, initial_population_snapshot_path: 'str | Path | None' = None, updated_population_snapshot_path: 'str | Path | None' = None, update_time_period: 'int | None' = None, fixed_record_path: 'str | Path | None' = None, keep_matching_patients_path: 'str | Path | None' = None, synthea_config: 'Mapping[str, str | int | float | bool] | None' = None, overwrite: 'bool' = False) -> 'Path'",
 'build_argv': "(self, java: 'Path', jar: 'Path', **settings) -> 'list[str]'",
 'get_available_config': "(jar_path: 'str | Path | None' = None, auto_download: 'bool' = True, pattern: 'str' = '*') -> 'dict[str, str | None]'"}

## 1. Discover supported Synthea configuration

These class methods work before a generator exists. `pattern` uses shell-style glob matching. Discovery reads `synthea.properties` from the actual pinned or explicitly supplied JAR, so it reflects the Synthea version that will run.

In [4]:
generation_properties = Synthea.get_available_config(
    pattern="generate.*"
)
list(sorted(generation_properties.items()))[:10]

[('generate.append_numbers_to_person_names', 'true'),
 ('generate.birthweights.default_file', 'birthweights.csv'),
 ('generate.birthweights.logging', 'false'),
 ('generate.costs.default_device_cost', '0.00'),
 ('generate.costs.default_encounter_cost', '125.00'),
 ('generate.costs.default_immunization_cost', '136.00'),
 ('generate.costs.default_lab_cost', '100.00'),
 ('generate.costs.default_medication_cost', '255.00'),
 ('generate.costs.default_procedure_cost', '500.00'),
 ('generate.costs.default_supply_cost', '0.00')]

The examples below use several ordinary Synthea properties:

- `generate.thread_pool_size=1` makes generation serial, so output is deterministic for a fixed seed;
- `generate.only_alive_patients=true` keeps only patients alive at the simulation end;
- `exporter.years_of_history=5` limits exported history;
- `exporter.csv.folder_per_run=false` keeps CSV files directly under the CSV directory; and
- `exporter.csv.append_mode=false` replaces rather than appends to prior CSV files.

CSV exporter selection and the output directory are managed by the wrapper and are rejected if placed in `synthea_config`.

## 2. Set up the generator

The constructor holds only setup. Population settings are passed to `generate()`, so one instance can produce any number of populations.

In [5]:
synthea = Synthea(output_dir=artifact_root / "generated", timeout=900)
synthea

Synthea(output_dir='/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated')

`build_argv()` shows the exact command `generate()` would run for some settings, without needing Java. Each distinct combination of settings is written to its own fingerprinted directory under `output_dir`, visible as `--exporter.baseDirectory`.

In [6]:
common_config = {
    "generate.thread_pool_size": 1,
    "generate.only_alive_patients": True,
    "exporter.years_of_history": 5,
    "exporter.csv.folder_per_run": False,
    "exporter.csv.append_mode": False,
}
settings = dict(
    population=10,
    seed=42,
    clinician_seed=43,
    reference_date="20240101",
    gender="F",
    age_range="30-40",
    overflow_population=False,
    state="Massachusetts",
    city="Boston",
    synthea_config=common_config,
)

preview_argv = synthea.build_argv(Path("java"), Path("synthea.jar"), **settings)
print(shlex.join(preview_argv))

java -jar synthea.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 42 -cs 43 -p 10 -r 20240101 -g F -a 30-40 -o false Massachusetts Boston

## 3. Generate several populations from one instance

Each call runs Synthea once and returns the CSV directory. Different settings go to different directories, so populations never overwrite each other.

In [7]:
csv_path = synthea.generate(**settings)
smaller_path = synthea.generate(population=3, seed=7, synthea_config=common_config)

assert csv_path != smaller_path
assert (csv_path / "patients.csv").is_file()
assert (smaller_path / "patients.csv").is_file()
sorted(path.name for path in csv_path.glob("*.csv"))

Running Synthea: /home/soham/.local/jvm/jdk-17.0.20.1+1/bin/java -jar /home/soham/.cache/pyhealth/synthea/synthea-with-dependencies-v4.0.0.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 42 -cs 43 -p 10 -r 20240101 -g F -a 30-40 -o false Massachusetts Boston

org.mitre.synthea.X12.ExporterAdaptor
org.mitre.synthea.X12.ExporterAdaptor

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

Scanned 92 modules and 449 submodules.
Loading submodule modules/allergies/allergy_panel.json
Loading submodule modules/allergies/drug_allergy_incidence.json

Loading submodule modules/allergies/environmental_allergy_incidence.json
Loading submodule modules/allergies/food_allergy_incidence.json
Loading submodule modules/allergies/immunotherapy.json
Loading submodule modules/allergies/outgrow_env_allergies.json
Loading submodule modules/allergies/outgrow_food_allergies.json
Loading submodule modules/allergies/severe_allergic_reaction.json
Loading submodule modules/anemia/anemia_sub.json

Loading submodule modules/breast_cancer/chemotherapy_breast.json
Loading submodule modules/breast_cancer/hormone_diagnosis.json
Loading submodule modules/breast_cancer/hormonetherapy_breast.json
Loading submodule modules/breast_cancer/surgery_therapy_breast.json
Loading submodule modules/breast_cancer/tnm_diagnosis.json
Loading submodule modules/contraceptives/clear_contraceptive.json
Loading submodule modules/contraceptives/female_sterilization.json
Loading submodule modules/contraceptives/implant_contraceptive.json
Loading submodule modules/contraceptives/injectable_contraceptive.json
Loading submodule modules/contraceptives/intrauterine_device.json
Loading submodule modules/contraceptives/male_sterilization.json

Loading submodule modules/contraceptives/oral_contraceptive.json
Loading submodule modules/contraceptives/patch_contraceptive.json
Loading submodule modules/contraceptives/ring_contraceptive.json
Loading submodule modules/covid19/admission.json
Loading submodule modules/covid19/determine_risk.json
Loading Lookup Table: covid-19-severity-outcomes.csv
Loading Lookup Table: covid-19-survival-outcomes.csv
Loading submodule modules/covid19/diagnose_bacterial_infection.json
Loading submodule modules/covid19/diagnose_blood_clot.json
Loading submodule modules/covid19/end_outcomes.json
Loading submodule modules/covid19/end_symptoms.json
Loading submodule modules/covid19/infection.json
Loading submodule modules/covid19/measurements_daily.json
Loading submodule modules/covid19/measurements_frequent.json
Loading submodule modules/covid19/measurements_vitals.json
Loading submodule modules/covid19/medications.json

Loading submodule modules/covid19/nonsurvivor_lab_values.json
Loading submodule modules/covid19/outcomes.json
Loading submodule modules/covid19/supplies_hospitalization.json
Loading submodule modules/covid19/supplies_icu.json
Loading submodule modules/covid19/supplies_intubation.json
Loading submodule modules/covid19/survivor_lab_values.json
Loading submodule modules/covid19/symptoms.json
Loading submodule modules/covid19/treat_blood_clot.json
Loading submodule modules/dental/dental_emergency.json
Loading submodule modules/dental/dental_encounter.json

Loading submodule modules/dental/dental_hospital.json
Loading submodule modules/dental/dental_telephone.json
Loading submodule modules/dental/diagnosis/cavity.json
Loading submodule modules/dental/diagnosis/dental disorder.json
Loading submodule modules/dental/diagnosis/gingivitis.json
Loading submodule modules/dental/diagnosis/periodontitis.json
Loading submodule modules/dental/diagnosis/plaque.json
Loading submodule modules/dental/end_dental_diagnoses.json
Loading submodule modules/dental/procedure/d01.json
Loading submodule modules/dental/procedure/d02.json
Loading submodule modules/dental/procedure/d03.json
Loading submodule modules/dental/procedure/d04.json
Loading submodule modules/dental/procedure/d05.json
Loading submodule modules/dental/procedure/d06.json
Loading submodule modules/dental/procedure/d09.json

Loading submodule modules/dental/procedure/d11.json
Loading submodule modules/dental/procedure/d12.json
Loading submodule modules/dental/procedure/d13.json
Loading submodule modules/dental/procedure/d15.json
Loading submodule modules/dental/procedure/d19.json
Loading submodule modules/dental/procedure/d21.json
Loading submodule modules/dental/procedure/d23.json
Loading submodule modules/dental/procedure/d25.json
Loading submodule modules/dental/procedure/d26.json
Loading submodule modules/dental/procedure/d27.json
Loading submodule modules/dental/procedure/d29.json
Loading submodule modules/dental/procedure/d31.json
Loading submodule modules/dental/procedure/d32.json
Loading submodule modules/dental/procedure/d33.json
Loading submodule modules/dental/procedure/d34.json
Loading submodule modules/dental/procedure/d39.json
Loading submodule modules/dental/procedure/d42.json
Loading submodule modules/dental/procedure/d43.json
Loading submodule modules/dental/procedure/d49.json
Loading submodule modules/dental/procedure/d51.json
Loading submodule modules/dental/procedure/d52.json
Loading submodule modules/dental/procedure/d54.json
Loading submodule modules/dental/procedure/d55.json
Loading submodule modules/dental/procedure/d56.json

Loading submodule modules/dental/procedure/d57.json
Loading submodule modules/dental/procedure/d58.json
Loading submodule modules/dental/procedure/d59.json
Loading submodule modules/dental/procedure/d60.json
Loading submodule modules/dental/procedure/d61.json
Loading submodule modules/dental/procedure/d62.json
Loading submodule modules/dental/procedure/d65.json
Loading submodule modules/dental/procedure/d66.json
Loading submodule modules/dental/procedure/d67.json
Loading submodule modules/dental/procedure/d69.json
Loading submodule modules/dental/procedure/d71.json
Loading submodule modules/dental/procedure/d72.json
Loading submodule modules/dental/procedure/d73.json
Loading submodule modules/dental/procedure/d74.json
Loading submodule modules/dental/procedure/d75.json
Loading submodule modules/dental/procedure/d76.json
Loading submodule modules/dental/procedure/d77.json
Loading submodule modules/dental/procedure/d78.json
Loading submodule modules/dental/procedure/d79.json
Loading submodule modules/dental/procedure/d80.json

Loading submodule modules/dental/procedure/d82.json
Loading submodule modules/dental/procedure/d86.json
Loading submodule modules/dental/procedure/d89.json
Loading submodule modules/dental/procedure/d91.json
Loading submodule modules/dental/procedure/d92.json
Loading submodule modules/dental/procedure/d93.json
Loading submodule modules/dental/procedure/d94.json
Loading submodule modules/dental/procedure/d96.json
Loading submodule modules/dental/procedure/d99.json
Loading submodule modules/dental_idr/dental_idr_cluster_0.json
Loading submodule modules/dental_idr/dental_idr_cluster_1.json

Loading submodule modules/dental_idr/dental_idr_cluster_2.json
Loading submodule modules/dental_idr/dental_idr_cluster_3.json
Loading submodule modules/dental_idr/dental_idr_cluster_4.json

Loading submodule modules/dental_idr/diagnosis/c00.json
Loading submodule modules/dental_idr/diagnosis/c01.json
Loading submodule modules/dental_idr/diagnosis/c02.json
Loading submodule modules/dental_idr/diagnosis/c03.json
Loading submodule modules/dental_idr/diagnosis/c04.json
Loading submodule modules/dental_idr/diagnosis/c05.json
Loading submodule modules/dental_idr/diagnosis/c06.json
Loading submodule modules/dental_idr/diagnosis/c07.json
Loading submodule modules/dental_idr/diagnosis/c08.json
Loading submodule modules/dental_idr/diagnosis/c09.json
Loading submodule modules/dental_idr/diagnosis/c10.json
Loading submodule modules/dental_idr/diagnosis/c11.json
Loading submodule modules/dental_idr/diagnosis/c12.json
Loading submodule modules/dental_idr/diagnosis/c13.json
Loading submodule modules/dental_idr/diagnosis/c14.json
Loading submodule modules/dental_idr/diagnosis/c15.json
Loading submodule modules/dental_idr/diagnosis/c16.json
Loading submodule modules/dental_idr/diagnosis/c17.json
Loading submodule modules/dental_idr/diagnosis/c18.json
Loading submodule modules/dental_idr/diagnosis/c19.json
Loading submodule modules/dental_idr/diagnosis/c20.json
Loading submodule modules/dental_idr/diagnosis/c21.json
Loading submodule modules/dental_idr/diagnosis/c22.json
Loading submodule modules/dental_idr/diagnosis/c24.json
Loading submodule modules/dental_idr/diagnosis/c25.json
Loading submodule modules/dental_idr/diagnosis/c26.json
Loading submodule modules/dental_idr/diagnosis/c30.json
Loading submodule modules/dental_idr/diagnosis/c31.json
Loading submodule modules/dental_idr/diagnosis/c32.json
Loading submodule modules/dental_idr/diagnosis/c33.json
Loading submodule modules/dental_idr/diagnosis/c34.json
Loading submodule modules/dental_idr/diagnosis/c37.json
Loading submodule modules/dental_idr/diagnosis/c38.json
Loading submodule modules/dental_idr/diagnosis/c39.json
Loading submodule modules/dental_idr/diagnosis/c40.json
Loading submodule modules/dental_idr/diagnosis/c41.json
Loading submodule modules/dental_idr/diagnosis/c43.json

Loading submodule modules/dental_idr/diagnosis/c44.json
Loading submodule modules/dental_idr/diagnosis/c45.json
Loading submodule modules/dental_idr/diagnosis/c46.json
Loading submodule modules/dental_idr/diagnosis/c47.json
Loading submodule modules/dental_idr/diagnosis/c48.json
Loading submodule modules/dental_idr/diagnosis/c49.json
Loading submodule modules/dental_idr/diagnosis/c4a.json
Loading submodule modules/dental_idr/diagnosis/c50.json
Loading submodule modules/dental_idr/diagnosis/c51.json
Loading submodule modules/dental_idr/diagnosis/c53.json
Loading submodule modules/dental_idr/diagnosis/c54.json
Loading submodule modules/dental_idr/diagnosis/c56.json
Loading submodule modules/dental_idr/diagnosis/c57.json
Loading submodule modules/dental_idr/diagnosis/c61.json
Loading submodule modules/dental_idr/diagnosis/c62.json
Loading submodule modules/dental_idr/diagnosis/c63.json
Loading submodule modules/dental_idr/diagnosis/c64.json
Loading submodule modules/dental_idr/diagnosis/c65.json
Loading submodule modules/dental_idr/diagnosis/c66.json
Loading submodule modules/dental_idr/diagnosis/c67.json
Loading submodule modules/dental_idr/diagnosis/c68.json
Loading submodule modules/dental_idr/diagnosis/c69.json
Loading submodule modules/dental_idr/diagnosis/c71.json
Loading submodule modules/dental_idr/diagnosis/c72.json
Loading submodule modules/dental_idr/diagnosis/c73.json
Loading submodule modules/dental_idr/diagnosis/c74.json
Loading submodule modules/dental_idr/diagnosis/c75.json
Loading submodule modules/dental_idr/diagnosis/c76.json

Loading submodule modules/dental_idr/diagnosis/c77.json
Loading submodule modules/dental_idr/diagnosis/c78.json
Loading submodule modules/dental_idr/diagnosis/c79.json
Loading submodule modules/dental_idr/diagnosis/c7a.json
Loading submodule modules/dental_idr/diagnosis/c7b.json
Loading submodule modules/dental_idr/diagnosis/c80.json
Loading submodule modules/dental_idr/diagnosis/c81.json
Loading submodule modules/dental_idr/diagnosis/c82.json
Loading submodule modules/dental_idr/diagnosis/c83.json
Loading submodule modules/dental_idr/diagnosis/c84.json
Loading submodule modules/dental_idr/diagnosis/c85.json
Loading submodule modules/dental_idr/diagnosis/c86.json
Loading submodule modules/dental_idr/diagnosis/c88.json
Loading submodule modules/dental_idr/diagnosis/c90.json
Loading submodule modules/dental_idr/diagnosis/c91.json
Loading submodule modules/dental_idr/diagnosis/c92.json
Loading submodule modules/dental_idr/diagnosis/c93.json
Loading submodule modules/dental_idr/diagnosis/c95.json
Loading submodule modules/dental_idr/diagnosis/c96.json
Loading submodule modules/dental_idr/diagnosis/d00.json
Loading submodule modules/dental_idr/diagnosis/d01.json
Loading submodule modules/dental_idr/diagnosis/d02.json
Loading submodule modules/dental_idr/diagnosis/d03.json
Loading submodule modules/dental_idr/diagnosis/d04.json
Loading submodule modules/dental_idr/diagnosis/d05.json
Loading submodule modules/dental_idr/diagnosis/d06.json

Loading submodule modules/dental_idr/diagnosis/d07.json
Loading submodule modules/dental_idr/diagnosis/d09.json
Loading submodule modules/dental_idr/diagnosis/d10.json
Loading submodule modules/dental_idr/diagnosis/d11.json
Loading submodule modules/dental_idr/diagnosis/d12.json
Loading submodule modules/dental_idr/diagnosis/d13.json
Loading submodule modules/dental_idr/diagnosis/d14.json
Loading submodule modules/dental_idr/diagnosis/d16.json
Loading submodule modules/dental_idr/diagnosis/d17.json
Loading submodule modules/dental_idr/diagnosis/d18.json
Loading submodule modules/dental_idr/diagnosis/d19.json
Loading submodule modules/dental_idr/diagnosis/d21.json
Loading submodule modules/dental_idr/diagnosis/d22.json
Loading submodule modules/dental_idr/diagnosis/d23.json
Loading submodule modules/dental_idr/diagnosis/d24.json
Loading submodule modules/dental_idr/diagnosis/d25.json
Loading submodule modules/dental_idr/diagnosis/d28.json
Loading submodule modules/dental_idr/diagnosis/d29.json
Loading submodule modules/dental_idr/diagnosis/d30.json
Loading submodule modules/dental_idr/diagnosis/d31.json
Loading submodule modules/dental_idr/diagnosis/d32.json
Loading submodule modules/dental_idr/diagnosis/d33.json
Loading submodule modules/dental_idr/diagnosis/d34.json
Loading submodule modules/dental_idr/diagnosis/d35.json
Loading submodule modules/dental_idr/diagnosis/d36.json
Loading submodule modules/dental_idr/diagnosis/d37.json
Loading submodule modules/dental_idr/diagnosis/d38.json
Loading submodule modules/dental_idr/diagnosis/d39.json
Loading submodule modules/dental_idr/diagnosis/d3a.json
Loading submodule modules/dental_idr/diagnosis/d40.json
Loading submodule modules/dental_idr/diagnosis/d41.json
Loading submodule modules/dental_idr/diagnosis/d44.json
Loading submodule modules/dental_idr/diagnosis/d45.json
Loading submodule modules/dental_idr/diagnosis/d46.json
Loading submodule modules/dental_idr/diagnosis/d47.json

Loading submodule modules/dental_idr/diagnosis/d48.json
Loading submodule modules/dental_idr/diagnosis/d49.json
Loading submodule modules/dental_idr/diagnosis/k00.json
Loading submodule modules/dental_idr/diagnosis/k01.json
Loading submodule modules/dental_idr/diagnosis/k02.json
Loading submodule modules/dental_idr/diagnosis/k03.json
Loading submodule modules/dental_idr/diagnosis/k04.json
Loading submodule modules/dental_idr/diagnosis/k05.json
Loading submodule modules/dental_idr/diagnosis/k06.json
Loading submodule modules/dental_idr/diagnosis/k08.json
Loading submodule modules/dental_idr/diagnosis/k09.json
Loading submodule modules/dental_idr/diagnosis/k11.json

Loading submodule modules/dental_idr/diagnosis/k12.json
Loading submodule modules/dental_idr/diagnosis/k13.json
Loading submodule modules/dental_idr/diagnosis/m26.json
Loading submodule modules/dental_idr/diagnosis/m27.json
Loading submodule modules/dental_idr/diagnosis/r69.json
Loading submodule modules/dental_idr/diagnosis/s02.json

Loading submodule modules/dental_idr/diagnosis/z00.json
Loading submodule modules/dental_idr/diagnosis/z01.json
Loading submodule modules/dental_idr/diagnosis/z13.json
Loading submodule modules/dental_idr/diagnosis/z40.json
Loading submodule modules/dental_idr/diagnosis/z41.json
Loading submodule modules/dental_idr/diagnosis/z51.json
Loading submodule modules/dental_idr/end_dental_diagnoses.json
Loading submodule modules/dental_idr/procedure/d01.json
Loading submodule modules/dental_idr/procedure/d02.json

Loading submodule modules/dental_idr/procedure/d03.json
Loading submodule modules/dental_idr/procedure/d04.json
Loading submodule modules/dental_idr/procedure/d05.json
Loading submodule modules/dental_idr/procedure/d06.json
Loading submodule modules/dental_idr/procedure/d07.json
Loading submodule modules/dental_idr/procedure/d08.json
Loading submodule modules/dental_idr/procedure/d09.json
Loading submodule modules/dental_idr/procedure/d11.json
Loading submodule modules/dental_idr/procedure/d12.json
Loading submodule modules/dental_idr/procedure/d13.json
Loading submodule modules/dental_idr/procedure/d15.json
Loading submodule modules/dental_idr/procedure/d17.json
Loading submodule modules/dental_idr/procedure/d19.json
Loading submodule modules/dental_idr/procedure/d21.json
Loading submodule modules/dental_idr/procedure/d23.json
Loading submodule modules/dental_idr/procedure/d24.json
Loading submodule modules/dental_idr/procedure/d25.json
Loading submodule modules/dental_idr/procedure/d26.json
Loading submodule modules/dental_idr/procedure/d27.json
Loading submodule modules/dental_idr/procedure/d29.json
Loading submodule modules/dental_idr/procedure/d31.json
Loading submodule modules/dental_idr/procedure/d32.json
Loading submodule modules/dental_idr/procedure/d33.json

Loading submodule modules/dental_idr/procedure/d34.json
Loading submodule modules/dental_idr/procedure/d35.json
Loading submodule modules/dental_idr/procedure/d39.json
Loading submodule modules/dental_idr/procedure/d42.json
Loading submodule modules/dental_idr/procedure/d43.json
Loading submodule modules/dental_idr/procedure/d49.json
Loading submodule modules/dental_idr/procedure/d51.json
Loading submodule modules/dental_idr/procedure/d52.json
Loading submodule modules/dental_idr/procedure/d54.json
Loading submodule modules/dental_idr/procedure/d55.json
Loading submodule modules/dental_idr/procedure/d56.json
Loading submodule modules/dental_idr/procedure/d57.json
Loading submodule modules/dental_idr/procedure/d58.json
Loading submodule modules/dental_idr/procedure/d59.json
Loading submodule modules/dental_idr/procedure/d60.json
Loading submodule modules/dental_idr/procedure/d61.json
Loading submodule modules/dental_idr/procedure/d62.json
Loading submodule modules/dental_idr/procedure/d65.json
Loading submodule modules/dental_idr/procedure/d66.json
Loading submodule modules/dental_idr/procedure/d67.json

Loading submodule modules/dental_idr/procedure/d69.json
Loading submodule modules/dental_idr/procedure/d71.json
Loading submodule modules/dental_idr/procedure/d72.json
Loading submodule modules/dental_idr/procedure/d73.json
Loading submodule modules/dental_idr/procedure/d74.json
Loading submodule modules/dental_idr/procedure/d75.json
Loading submodule modules/dental_idr/procedure/d76.json
Loading submodule modules/dental_idr/procedure/d77.json
Loading submodule modules/dental_idr/procedure/d78.json
Loading submodule modules/dental_idr/procedure/d79.json
Loading submodule modules/dental_idr/procedure/d80.json
Loading submodule modules/dental_idr/procedure/d82.json
Loading submodule modules/dental_idr/procedure/d86.json
Loading submodule modules/dental_idr/procedure/d87.json
Loading submodule modules/dental_idr/procedure/d89.json
Loading submodule modules/dental_idr/procedure/d91.json
Loading submodule modules/dental_idr/procedure/d92.json
Loading submodule modules/dental_idr/procedure/d93.json
Loading submodule modules/dental_idr/procedure/d94.json
Loading submodule modules/dental_idr/procedure/d96.json
Loading submodule modules/dental_idr/procedure/d99.json
Loading submodule modules/dermatitis/early_moderate_eczema_obs.json
Loading submodule modules/dermatitis/early_severe_eczema_obs.json
Loading submodule modules/dermatitis/mid_moderate_eczema_obs.json
Loading submodule modules/dermatitis/mid_severe_eczema_obs.json

Loading submodule modules/dermatitis/moderate_cd_obs.json
Loading submodule modules/dermatitis/severe_cd_obs.json
Loading submodule modules/dme/wheelchair.json
Loading submodule modules/dme/wheelchair_end.json
Loading submodule modules/encounter/anxiety_screening.json
Loading submodule modules/encounter/depression_screening.json
Loading submodule modules/encounter/fall_risk_screening.json
Loading submodule modules/encounter/hark_screening.json
Loading submodule modules/encounter/hospital_basic_labs.json
Loading submodule modules/encounter/sdoh_hrsn.json
Loading submodule modules/encounter/substance_use_screening.json
Loading submodule modules/encounter/vitals.json
Loading submodule modules/eye/intraocular_pressure.json
Loading submodule modules/eye/ophthalmic_progression.json

Loading submodule modules/eye/ophthalmic_tomography.json
Loading submodule modules/eye/visual_acuity.json
Loading submodule modules/heart/acs_anticoagulant.json
Loading submodule modules/heart/acs_antiplatelet.json
Loading submodule modules/heart/acs_arrival_medications.json
Loading submodule modules/heart/acs_discharge_meds.json
Loading submodule modules/heart/avrr/antithrombotic.json
Loading submodule modules/heart/avrr/avrr_referral.json
Loading submodule modules/heart/avrr/intraop_meds_blood.json
Loading submodule modules/heart/avrr/outcomes.json
Loading submodule modules/heart/avrr/preoperative.json
Loading submodule modules/heart/avrr/savrr_operation.json
Loading submodule modules/heart/avrr/savrr_postop.json
Loading submodule modules/heart/avrr/sequence.json
Loading submodule modules/heart/cabg/cabg_referral.json
Loading submodule modules/heart/cabg/details.json
Loading Lookup Table: cabg_details_operative_approach.csv
Loading Lookup Table: cabg_details_num_grafts.csv
Loading Lookup Table: cabg_details_num_art_cond.csv

Loading submodule modules/heart/cabg/icu_meds_devices.json
Loading submodule modules/heart/cabg/labs_common.json
Loading submodule modules/heart/cabg/operation.json
Loading submodule modules/heart/cabg/or_intraop.json
Loading submodule modules/heart/cabg/or_labs_meds.json
Loading submodule modules/heart/cabg/outcomes.json
Loading submodule modules/heart/cabg/postop.json
Loading submodule modules/heart/cabg/postop_blood.json
Loading submodule modules/heart/cabg/preoperative.json
Loading submodule modules/heart/cabg_sequence.json
Loading submodule modules/heart/cardiac_labs.json
Loading submodule modules/heart/chf_lab_work.json
Loading submodule modules/heart/chf_lvad.json
Loading submodule modules/heart/chf_meds.json
Loading submodule modules/heart/chf_meds_hfmef.json
Loading submodule modules/heart/chf_meds_hfref_nyha2.json
Loading submodule modules/heart/chf_meds_hfref_nyha3.json
Loading submodule modules/heart/chf_meds_hfref_nyha4.json
Loading submodule modules/heart/chf_nyha_panel.json
Loading submodule modules/heart/chf_transplant.json

Loading submodule modules/heart/nsteacs_pathway.json
Loading submodule modules/heart/operative_status.json
Loading submodule modules/heart/or_blood.json
Loading Lookup Table: or_blood_anemia_check.csv
Loading Lookup Table: or_blood_platelet_check.csv
Loading Lookup Table: or_blood_plasma_check.csv
Loading submodule modules/heart/savrepair/operative_status.json
Loading submodule modules/heart/savreplace/operative_status.json
Loading submodule modules/heart/stemi_fibrinolytic.json
Loading submodule modules/heart/stemi_pathway.json
Loading submodule modules/heart/tavr/alt_access.json
Loading submodule modules/heart/tavr/operation.json
Loading submodule modules/heart/tavr/operative_status.json
Loading submodule modules/heart/tavr/outcomes.json
Loading submodule modules/heart/tavr/postop.json
Loading submodule modules/heart/vhd_risks.json
Loading submodule modules/hiv/art_sequence.json
Loading submodule modules/hiv/art_sequence_1987_1994.json
Loading submodule modules/hiv/art_sequence_1995_1996.json
Loading submodule modules/hiv/art_sequence_1997_2002.json
Loading submodule modules/hiv/art_sequence_2003_2005.json
Loading submodule modules/hiv/art_sequence_2006_2014.json

Loading submodule modules/hiv/art_sequence_2015.json
Loading submodule modules/hiv/hiv_baseline.json
Loading submodule modules/hiv/hiv_cd4.json
Loading Lookup Table: hiv_stage.csv
Loading submodule modules/hiv/hiv_oi_prophylaxis.json
Loading submodule modules/hiv/hiv_screening.json
Loading submodule modules/hiv/hiv_viral_load.json
Loading submodule modules/hiv/stop_all_art_meds.json
Loading submodule modules/injuries/broken_jaw.json
Loading submodule modules/lung_cancer/lung_cancer_probabilities.json
Loading submodule modules/medications/ace_arb.json
Loading Lookup Table: ace_arb_ingredient_distribution.csv
Loading Lookup Table: ace_arb_amlodipine_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: ace_arb_enalapril_product_distribution.csv

Loading Lookup Table: ace_arb_hydrochlorothiazide_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_irbesartan_product_distribution.csv
Loading Lookup Table: ace_arb_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_quinapril_product_distribution.csv
Loading Lookup Table: ace_arb_ramipril_product_distribution.csv
Loading Lookup Table: ace_arb_sacubitril_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_telmisartan_product_distribution.csv
Loading Lookup Table: ace_arb_valsartan_product_distribution.csv
Loading submodule modules/medications/beta_blocker.json
Loading Lookup Table: beta_blocker_ingredient_distribution.csv
Loading Lookup Table: beta_blocker_atenolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: beta_blocker_carvedilol_product_distribution.csv
Loading Lookup Table: beta_blocker_labetalol_product_distribution.csv
Loading Lookup Table: beta_blocker_metoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_nebivolol_product_distribution.csv
Loading Lookup Table: beta_blocker_propranolol_product_distribution.csv
Loading submodule modules/medications/ear_infection_antibiotic.json
Loading submodule modules/medications/emergency_inhaler.json
Loading Lookup Table: emergency_inhaler_ingredient_distribution.csv
Loading Lookup Table: emergency_inhaler_albuterol_product_distribution.csv
Loading Lookup Table: emergency_inhaler_levalbuterol_product_distribution.csv
Loading submodule modules/medications/hypertension_medication.json
Loading submodule modules/medications/maintenance_inhaler.json
Loading Lookup Table: maintenance_inhaler_ingredient_distribution.csv
Loading Lookup Table: maintenance_inhaler_beclomethasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_budesonide_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_fluticasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_mometasone_product_distribution.csv
Loading submodule modules/medications/moderate_opioid_pain_reliever.json
Loading submodule modules/medications/otc_antihistamine.json
Loading submodule modules/medications/otc_pain_reliever.json
Loading submodule modules/medications/statin.json
Loading Lookup Table: statin_ingredient_distribution.csv

Loading Lookup Table: statin_atorvastatin_product_distribution.csv
Loading Lookup Table: statin_ezetimibe_simvastatin_product_distribution.csv
Loading Lookup Table: statin_lovastatin_product_distribution.csv
Loading Lookup Table: statin_pitavastatin_product_distribution.csv
Loading Lookup Table: statin_pravastatin_product_distribution.csv
Loading Lookup Table: statin_rosuvastatin_product_distribution.csv
Loading Lookup Table: statin_simvastatin_product_distribution.csv
Loading submodule modules/medications/strong_opioid_pain_reliever.json
Loading submodule modules/metabolic_syndrome/amputations.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_diagnoses.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_progression.json
Loading submodule modules/metabolic_syndrome/dme_supplies.json
Loading submodule modules/metabolic_syndrome/kidney_conditions.json
Loading submodule modules/metabolic_syndrome/medications.json
Loading submodule modules/snf/skilled_nursing_facility.json
Loading submodule modules/surgery/general_anesthesia.json
Loading submodule modules/total_joint_replacement/functional_status_assessments.json
Loading submodule modules/uti/abx_tx.json
Loading submodule modules/uti/ambulatory_eval.json
Loading submodule modules/uti/ambulatory_path.json
Loading submodule modules/uti/ed_bundle.json

Loading submodule modules/uti/ed_eval.json
Loading submodule modules/uti/ed_path.json
Loading submodule modules/uti/gu_pregnancy_check.json
Loading submodule modules/uti/hpi.json
Loading submodule modules/uti/lab_follow_up.json
Loading submodule modules/uti/labs.json
Loading submodule modules/uti/telemed_path.json
Loading submodule modules/veterans/veteran_suicide_probabilities.json
Loading submodule modules/weight_loss/mend_week.json
Loading module modules/AIS_From_School_Screening_to_SOSORT_Recommendations.json
Loading module modules/acute_myeloid_leukemia.json
Loading Lookup Table: AML.csv
Loading module modules/allergic_rhinitis.json
Loading module modules/allergies.json

Loading module modules/anemia___unknown_etiology.json
Loading module modules/appendicitis.json
Loading module modules/asthma.json
Loading module modules/atopy.json
Loading module modules/atrial_fibrillation.json
Loading module modules/attention_deficit_disorder.json
Loading module modules/bone_marrow_transplant.json
Loading module modules/breast_cancer.json
Loading module modules/bronchitis.json

Loading module modules/cerebral_palsy.json
Loading module modules/chronic_kidney_disease.json
Loading module modules/colorectal_cancer.json
Loading module modules/congestive_heart_failure.json

Loading module modules/contraceptive_maintenance.json
Loading module modules/contraceptives.json
Loading module modules/copd.json
Loading module modules/covid19.json
Loading Lookup Table: covid19_prob.csv
Loading module modules/cystic_fibrosis.json
Loading module modules/dementia.json
Loading module modules/dental_and_oral_examination.json

Loading module modules/dental_encounters.json
Loading module modules/dental_medicare_clustered_encounters.json
Loading module modules/dentures.json
Loading module modules/dermatitis.json
Loading module modules/diabetic_retinopathy_treatment.json
Loading Lookup Table: diabetic_retinopathy_followup.csv
Loading module modules/dialysis.json
Loading module modules/ear_infections.json
Loading module modules/epilepsy.json
Loading module modules/female_reproduction.json
Loading module modules/fibromyalgia.json
Loading module modules/food_allergies.json
Loading module modules/gallstones.json

Loading module modules/gout.json
Loading module modules/hiv_care.json
Loading Lookup Table: hiv_care.csv
Loading module modules/hiv_diagnosis.json
Loading Lookup Table: hiv_mortality_later.csv
Loading Lookup Table: hiv_mortality_early.csv
Loading Lookup Table: hiv_mortality_very_early.csv
Loading Lookup Table: hiv_diagnosis_early.csv
Loading Lookup Table: hiv_diagnosis_later.csv
Loading module modules/home_health_treatment.json
Loading module modules/home_hospice_snf.json
Loading module modules/homelessness.json
Loading module modules/hospice_treatment.json
Loading module modules/hypertension.json
Loading module modules/hypothyroidism.json
Loading module modules/injuries.json

Loading module modules/kidney_transplant.json
Loading module modules/lung_cancer.json
Loading module modules/lupus.json
Loading module modules/mTBI.json
Loading module modules/med_rec.json
Loading module modules/mend_program.json
Loading module modules/metabolic_syndrome_care.json
Loading module modules/metabolic_syndrome_disease.json
Loading module modules/myocardial_infarction.json
Loading module modules/opioid_addiction.json

Loading module modules/osteoarthritis.json
Loading module modules/osteoporosis.json
Loading module modules/pregnancy.json
Loading module modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json

Loading module modules/rheumatoid_arthritis.json
Loading module modules/self_harm.json
Loading module modules/sepsis.json
Loading module modules/sexual_activity.json
Loading module modules/sinusitis.json
Loading module modules/sleep_apnea.json
Loading module modules/sore_throat.json
Loading module modules/spina_bifida.json
Loading module modules/stable_ischemic_heart_disease.json

Loading module modules/stroke.json
Loading module modules/total_joint_replacement.json
Loading module modules/trigger_bone_marrow_transplant.json
Loading module modules/urinary_tract_infections.json
Loading Lookup Table: uti.csv
Loading Lookup Table: uti_recurrence.csv
Loading module modules/veteran.json
Loading module modules/veteran_hyperlipidemia.json
Loading module modules/veteran_lung_cancer.json
Loading module modules/veteran_mdd.json
Loading module modules/veteran_prostate_cancer.json
Loading module modules/veteran_ptsd.json

Loading module modules/veteran_self_harm.json
Loading module modules/veteran_substance_abuse_conditions.json
Loading module modules/veteran_substance_abuse_treatment.json
Loading module modules/vhd_aortic.json
Loading Lookup Table: vhd_as.csv
Loading Lookup Table: vhd_ar.csv
Loading module modules/vhd_mitral.json
Loading Lookup Table: vhd_mr.csv
Loading Lookup Table: vhd_ms.csv
Loading module modules/vhd_pulmonic.json
Loading Lookup Table: vhd_ps.csv
Loading Lookup Table: vhd_pr.csv
Loading module modules/vhd_tricuspid.json
Loading Lookup Table: vhd_tr.csv
Loading Lookup Table: vhd_ts.csv
Loading module modules/wellness_encounters.json
Running with options:
Population: 10
Seed: 42
Provider Seed:43
Reference Time: 1704067200000
Location: Boston, Massachusetts
Min Age: 30
Max Age: 40
Gender: F

1 -- Corie618 Sofia418 Rath779 (40 y/o F) Boston, Massachusetts  (55751)

2 -- Antonia30 Rosa195 Tapia475 (41 y/o F) Boston, Massachusetts  (55585)
3 -- Lola232 Ariadna374 Cardona494 (37 y/o F) Boston, Massachusetts  (50158)

4 -- Esperanza675 María Luisa888 Valverde277 (32 y/o F) Boston, Massachusetts  (45515)
5 -- Jona712 Bonnie873 Rosenbaum794 (35 y/o F) Boston, Massachusetts  (51640)

6 -- Tennille443 Denna536 Nitzsche158 (36 y/o F) Boston, Massachusetts  (49197)
7 -- Ocie984 Bernie827 Homenick806 (40 y/o F) Boston, Massachusetts  (56300)

8 -- Lindsay928 Deja232 Pollich983 (38 y/o F) Boston, Massachusetts  (52138)
9 -- Shondra529 Kyra237 Spinka232 (34 y/o F) Boston, Massachusetts  (46387)

10 -- Chrissy459 Jolynn62 Stanton715 (40 y/o F) Boston, Massachusetts  (58930)

Records: total=10, alive=10, dead=0
RNG=10
Clinician RNG=5638

You've just generated 10 patients! We're happy to know Synthea is helping you with your project.
Like what we're doing? Synthea is an open-source project, and your support helps us keep building.
Please consider ]8;;https://github.com/sponsors/synthetichealthmaking a donation]8;; (https://github.com/sponsors/synthetichealth).

Running Synthea: /home/soham/.local/jvm/jdk-17.0.20.1+1/bin/java -jar /home/soham/.cache/pyhealth/synthea/synthea-with-dependencies-v4.0.0.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/36cf651f1ef161fa3ee3de791f868b850be4dda4485fe4f0772e1d7dfbcb38bf --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 7 -p 3

org.mitre.synthea.X12.ExporterAdaptor
org.mitre.synthea.X12.ExporterAdaptor

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

Scanned 92 modules and 449 submodules.
Loading submodule modules/allergies/allergy_panel.json
Loading submodule modules/allergies/drug_allergy_incidence.json
Loading submodule modules/allergies/environmental_allergy_incidence.json

Loading submodule modules/allergies/food_allergy_incidence.json
Loading submodule modules/allergies/immunotherapy.json
Loading submodule modules/allergies/outgrow_env_allergies.json
Loading submodule modules/allergies/outgrow_food_allergies.json
Loading submodule modules/allergies/severe_allergic_reaction.json
Loading submodule modules/anemia/anemia_sub.json
Loading submodule modules/breast_cancer/chemotherapy_breast.json
Loading submodule modules/breast_cancer/hormone_diagnosis.json
Loading submodule modules/breast_cancer/hormonetherapy_breast.json

Loading submodule modules/breast_cancer/surgery_therapy_breast.json
Loading submodule modules/breast_cancer/tnm_diagnosis.json
Loading submodule modules/contraceptives/clear_contraceptive.json
Loading submodule modules/contraceptives/female_sterilization.json
Loading submodule modules/contraceptives/implant_contraceptive.json
Loading submodule modules/contraceptives/injectable_contraceptive.json
Loading submodule modules/contraceptives/intrauterine_device.json
Loading submodule modules/contraceptives/male_sterilization.json
Loading submodule modules/contraceptives/oral_contraceptive.json
Loading submodule modules/contraceptives/patch_contraceptive.json
Loading submodule modules/contraceptives/ring_contraceptive.json
Loading submodule modules/covid19/admission.json

Loading submodule modules/covid19/determine_risk.json
Loading Lookup Table: covid-19-severity-outcomes.csv
Loading Lookup Table: covid-19-survival-outcomes.csv
Loading submodule modules/covid19/diagnose_bacterial_infection.json
Loading submodule modules/covid19/diagnose_blood_clot.json
Loading submodule modules/covid19/end_outcomes.json
Loading submodule modules/covid19/end_symptoms.json
Loading submodule modules/covid19/infection.json
Loading submodule modules/covid19/measurements_daily.json
Loading submodule modules/covid19/measurements_frequent.json
Loading submodule modules/covid19/measurements_vitals.json
Loading submodule modules/covid19/medications.json
Loading submodule modules/covid19/nonsurvivor_lab_values.json

Loading submodule modules/covid19/outcomes.json
Loading submodule modules/covid19/supplies_hospitalization.json
Loading submodule modules/covid19/supplies_icu.json
Loading submodule modules/covid19/supplies_intubation.json
Loading submodule modules/covid19/survivor_lab_values.json
Loading submodule modules/covid19/symptoms.json
Loading submodule modules/covid19/treat_blood_clot.json
Loading submodule modules/dental/dental_emergency.json
Loading submodule modules/dental/dental_encounter.json

Loading submodule modules/dental/dental_hospital.json
Loading submodule modules/dental/dental_telephone.json
Loading submodule modules/dental/diagnosis/cavity.json
Loading submodule modules/dental/diagnosis/dental disorder.json
Loading submodule modules/dental/diagnosis/gingivitis.json
Loading submodule modules/dental/diagnosis/periodontitis.json
Loading submodule modules/dental/diagnosis/plaque.json
Loading submodule modules/dental/end_dental_diagnoses.json
Loading submodule modules/dental/procedure/d01.json
Loading submodule modules/dental/procedure/d02.json
Loading submodule modules/dental/procedure/d03.json
Loading submodule modules/dental/procedure/d04.json
Loading submodule modules/dental/procedure/d05.json
Loading submodule modules/dental/procedure/d06.json

Loading submodule modules/dental/procedure/d09.json
Loading submodule modules/dental/procedure/d11.json
Loading submodule modules/dental/procedure/d12.json
Loading submodule modules/dental/procedure/d13.json
Loading submodule modules/dental/procedure/d15.json
Loading submodule modules/dental/procedure/d19.json
Loading submodule modules/dental/procedure/d21.json
Loading submodule modules/dental/procedure/d23.json
Loading submodule modules/dental/procedure/d25.json
Loading submodule modules/dental/procedure/d26.json
Loading submodule modules/dental/procedure/d27.json
Loading submodule modules/dental/procedure/d29.json
Loading submodule modules/dental/procedure/d31.json
Loading submodule modules/dental/procedure/d32.json
Loading submodule modules/dental/procedure/d33.json
Loading submodule modules/dental/procedure/d34.json
Loading submodule modules/dental/procedure/d39.json
Loading submodule modules/dental/procedure/d42.json
Loading submodule modules/dental/procedure/d43.json
Loading submodule modules/dental/procedure/d49.json
Loading submodule modules/dental/procedure/d51.json
Loading submodule modules/dental/procedure/d52.json
Loading submodule modules/dental/procedure/d54.json
Loading submodule modules/dental/procedure/d55.json
Loading submodule modules/dental/procedure/d56.json

Loading submodule modules/dental/procedure/d57.json
Loading submodule modules/dental/procedure/d58.json
Loading submodule modules/dental/procedure/d59.json
Loading submodule modules/dental/procedure/d60.json
Loading submodule modules/dental/procedure/d61.json
Loading submodule modules/dental/procedure/d62.json
Loading submodule modules/dental/procedure/d65.json
Loading submodule modules/dental/procedure/d66.json
Loading submodule modules/dental/procedure/d67.json
Loading submodule modules/dental/procedure/d69.json
Loading submodule modules/dental/procedure/d71.json
Loading submodule modules/dental/procedure/d72.json
Loading submodule modules/dental/procedure/d73.json
Loading submodule modules/dental/procedure/d74.json
Loading submodule modules/dental/procedure/d75.json
Loading submodule modules/dental/procedure/d76.json
Loading submodule modules/dental/procedure/d77.json
Loading submodule modules/dental/procedure/d78.json
Loading submodule modules/dental/procedure/d79.json
Loading submodule modules/dental/procedure/d80.json
Loading submodule modules/dental/procedure/d82.json
Loading submodule modules/dental/procedure/d86.json
Loading submodule modules/dental/procedure/d89.json
Loading submodule modules/dental/procedure/d91.json
Loading submodule modules/dental/procedure/d92.json
Loading submodule modules/dental/procedure/d93.json

Loading submodule modules/dental/procedure/d94.json
Loading submodule modules/dental/procedure/d96.json
Loading submodule modules/dental/procedure/d99.json
Loading submodule modules/dental_idr/dental_idr_cluster_0.json
Loading submodule modules/dental_idr/dental_idr_cluster_1.json
Loading submodule modules/dental_idr/dental_idr_cluster_2.json

Loading submodule modules/dental_idr/dental_idr_cluster_3.json
Loading submodule modules/dental_idr/dental_idr_cluster_4.json

Loading submodule modules/dental_idr/diagnosis/c00.json
Loading submodule modules/dental_idr/diagnosis/c01.json
Loading submodule modules/dental_idr/diagnosis/c02.json
Loading submodule modules/dental_idr/diagnosis/c03.json
Loading submodule modules/dental_idr/diagnosis/c04.json
Loading submodule modules/dental_idr/diagnosis/c05.json
Loading submodule modules/dental_idr/diagnosis/c06.json
Loading submodule modules/dental_idr/diagnosis/c07.json
Loading submodule modules/dental_idr/diagnosis/c08.json
Loading submodule modules/dental_idr/diagnosis/c09.json
Loading submodule modules/dental_idr/diagnosis/c10.json
Loading submodule modules/dental_idr/diagnosis/c11.json
Loading submodule modules/dental_idr/diagnosis/c12.json
Loading submodule modules/dental_idr/diagnosis/c13.json
Loading submodule modules/dental_idr/diagnosis/c14.json
Loading submodule modules/dental_idr/diagnosis/c15.json
Loading submodule modules/dental_idr/diagnosis/c16.json
Loading submodule modules/dental_idr/diagnosis/c17.json
Loading submodule modules/dental_idr/diagnosis/c18.json
Loading submodule modules/dental_idr/diagnosis/c19.json
Loading submodule modules/dental_idr/diagnosis/c20.json
Loading submodule modules/dental_idr/diagnosis/c21.json
Loading submodule modules/dental_idr/diagnosis/c22.json
Loading submodule modules/dental_idr/diagnosis/c24.json
Loading submodule modules/dental_idr/diagnosis/c25.json
Loading submodule modules/dental_idr/diagnosis/c26.json
Loading submodule modules/dental_idr/diagnosis/c30.json
Loading submodule modules/dental_idr/diagnosis/c31.json
Loading submodule modules/dental_idr/diagnosis/c32.json
Loading submodule modules/dental_idr/diagnosis/c33.json
Loading submodule modules/dental_idr/diagnosis/c34.json
Loading submodule modules/dental_idr/diagnosis/c37.json
Loading submodule modules/dental_idr/diagnosis/c38.json
Loading submodule modules/dental_idr/diagnosis/c39.json
Loading submodule modules/dental_idr/diagnosis/c40.json
Loading submodule modules/dental_idr/diagnosis/c41.json
Loading submodule modules/dental_idr/diagnosis/c43.json
Loading submodule modules/dental_idr/diagnosis/c44.json
Loading submodule modules/dental_idr/diagnosis/c45.json
Loading submodule modules/dental_idr/diagnosis/c46.json

Loading submodule modules/dental_idr/diagnosis/c47.json
Loading submodule modules/dental_idr/diagnosis/c48.json
Loading submodule modules/dental_idr/diagnosis/c49.json
Loading submodule modules/dental_idr/diagnosis/c4a.json
Loading submodule modules/dental_idr/diagnosis/c50.json
Loading submodule modules/dental_idr/diagnosis/c51.json
Loading submodule modules/dental_idr/diagnosis/c53.json
Loading submodule modules/dental_idr/diagnosis/c54.json
Loading submodule modules/dental_idr/diagnosis/c56.json
Loading submodule modules/dental_idr/diagnosis/c57.json
Loading submodule modules/dental_idr/diagnosis/c61.json
Loading submodule modules/dental_idr/diagnosis/c62.json
Loading submodule modules/dental_idr/diagnosis/c63.json
Loading submodule modules/dental_idr/diagnosis/c64.json
Loading submodule modules/dental_idr/diagnosis/c65.json
Loading submodule modules/dental_idr/diagnosis/c66.json
Loading submodule modules/dental_idr/diagnosis/c67.json
Loading submodule modules/dental_idr/diagnosis/c68.json
Loading submodule modules/dental_idr/diagnosis/c69.json
Loading submodule modules/dental_idr/diagnosis/c71.json
Loading submodule modules/dental_idr/diagnosis/c72.json
Loading submodule modules/dental_idr/diagnosis/c73.json
Loading submodule modules/dental_idr/diagnosis/c74.json
Loading submodule modules/dental_idr/diagnosis/c75.json
Loading submodule modules/dental_idr/diagnosis/c76.json
Loading submodule modules/dental_idr/diagnosis/c77.json
Loading submodule modules/dental_idr/diagnosis/c78.json
Loading submodule modules/dental_idr/diagnosis/c79.json
Loading submodule modules/dental_idr/diagnosis/c7a.json
Loading submodule modules/dental_idr/diagnosis/c7b.json
Loading submodule modules/dental_idr/diagnosis/c80.json
Loading submodule modules/dental_idr/diagnosis/c81.json
Loading submodule modules/dental_idr/diagnosis/c82.json
Loading submodule modules/dental_idr/diagnosis/c83.json

Loading submodule modules/dental_idr/diagnosis/c84.json
Loading submodule modules/dental_idr/diagnosis/c85.json
Loading submodule modules/dental_idr/diagnosis/c86.json
Loading submodule modules/dental_idr/diagnosis/c88.json
Loading submodule modules/dental_idr/diagnosis/c90.json
Loading submodule modules/dental_idr/diagnosis/c91.json
Loading submodule modules/dental_idr/diagnosis/c92.json
Loading submodule modules/dental_idr/diagnosis/c93.json
Loading submodule modules/dental_idr/diagnosis/c95.json
Loading submodule modules/dental_idr/diagnosis/c96.json
Loading submodule modules/dental_idr/diagnosis/d00.json
Loading submodule modules/dental_idr/diagnosis/d01.json
Loading submodule modules/dental_idr/diagnosis/d02.json
Loading submodule modules/dental_idr/diagnosis/d03.json
Loading submodule modules/dental_idr/diagnosis/d04.json
Loading submodule modules/dental_idr/diagnosis/d05.json
Loading submodule modules/dental_idr/diagnosis/d06.json
Loading submodule modules/dental_idr/diagnosis/d07.json
Loading submodule modules/dental_idr/diagnosis/d09.json
Loading submodule modules/dental_idr/diagnosis/d10.json
Loading submodule modules/dental_idr/diagnosis/d11.json
Loading submodule modules/dental_idr/diagnosis/d12.json
Loading submodule modules/dental_idr/diagnosis/d13.json
Loading submodule modules/dental_idr/diagnosis/d14.json
Loading submodule modules/dental_idr/diagnosis/d16.json
Loading submodule modules/dental_idr/diagnosis/d17.json
Loading submodule modules/dental_idr/diagnosis/d18.json
Loading submodule modules/dental_idr/diagnosis/d19.json
Loading submodule modules/dental_idr/diagnosis/d21.json
Loading submodule modules/dental_idr/diagnosis/d22.json
Loading submodule modules/dental_idr/diagnosis/d23.json

Loading submodule modules/dental_idr/diagnosis/d24.json
Loading submodule modules/dental_idr/diagnosis/d25.json
Loading submodule modules/dental_idr/diagnosis/d28.json
Loading submodule modules/dental_idr/diagnosis/d29.json
Loading submodule modules/dental_idr/diagnosis/d30.json
Loading submodule modules/dental_idr/diagnosis/d31.json
Loading submodule modules/dental_idr/diagnosis/d32.json
Loading submodule modules/dental_idr/diagnosis/d33.json
Loading submodule modules/dental_idr/diagnosis/d34.json
Loading submodule modules/dental_idr/diagnosis/d35.json
Loading submodule modules/dental_idr/diagnosis/d36.json
Loading submodule modules/dental_idr/diagnosis/d37.json
Loading submodule modules/dental_idr/diagnosis/d38.json
Loading submodule modules/dental_idr/diagnosis/d39.json
Loading submodule modules/dental_idr/diagnosis/d3a.json
Loading submodule modules/dental_idr/diagnosis/d40.json
Loading submodule modules/dental_idr/diagnosis/d41.json
Loading submodule modules/dental_idr/diagnosis/d44.json
Loading submodule modules/dental_idr/diagnosis/d45.json
Loading submodule modules/dental_idr/diagnosis/d46.json
Loading submodule modules/dental_idr/diagnosis/d47.json
Loading submodule modules/dental_idr/diagnosis/d48.json
Loading submodule modules/dental_idr/diagnosis/d49.json
Loading submodule modules/dental_idr/diagnosis/k00.json
Loading submodule modules/dental_idr/diagnosis/k01.json
Loading submodule modules/dental_idr/diagnosis/k02.json
Loading submodule modules/dental_idr/diagnosis/k03.json
Loading submodule modules/dental_idr/diagnosis/k04.json
Loading submodule modules/dental_idr/diagnosis/k05.json

Loading submodule modules/dental_idr/diagnosis/k06.json
Loading submodule modules/dental_idr/diagnosis/k08.json
Loading submodule modules/dental_idr/diagnosis/k09.json
Loading submodule modules/dental_idr/diagnosis/k11.json
Loading submodule modules/dental_idr/diagnosis/k12.json
Loading submodule modules/dental_idr/diagnosis/k13.json
Loading submodule modules/dental_idr/diagnosis/m26.json
Loading submodule modules/dental_idr/diagnosis/m27.json

Loading submodule modules/dental_idr/diagnosis/r69.json
Loading submodule modules/dental_idr/diagnosis/s02.json
Loading submodule modules/dental_idr/diagnosis/z00.json
Loading submodule modules/dental_idr/diagnosis/z01.json
Loading submodule modules/dental_idr/diagnosis/z13.json
Loading submodule modules/dental_idr/diagnosis/z40.json
Loading submodule modules/dental_idr/diagnosis/z41.json

Loading submodule modules/dental_idr/diagnosis/z51.json
Loading submodule modules/dental_idr/end_dental_diagnoses.json
Loading submodule modules/dental_idr/procedure/d01.json
Loading submodule modules/dental_idr/procedure/d02.json
Loading submodule modules/dental_idr/procedure/d03.json
Loading submodule modules/dental_idr/procedure/d04.json

Loading submodule modules/dental_idr/procedure/d05.json
Loading submodule modules/dental_idr/procedure/d06.json
Loading submodule modules/dental_idr/procedure/d07.json
Loading submodule modules/dental_idr/procedure/d08.json
Loading submodule modules/dental_idr/procedure/d09.json
Loading submodule modules/dental_idr/procedure/d11.json
Loading submodule modules/dental_idr/procedure/d12.json
Loading submodule modules/dental_idr/procedure/d13.json
Loading submodule modules/dental_idr/procedure/d15.json
Loading submodule modules/dental_idr/procedure/d17.json
Loading submodule modules/dental_idr/procedure/d19.json
Loading submodule modules/dental_idr/procedure/d21.json
Loading submodule modules/dental_idr/procedure/d23.json
Loading submodule modules/dental_idr/procedure/d24.json
Loading submodule modules/dental_idr/procedure/d25.json
Loading submodule modules/dental_idr/procedure/d26.json
Loading submodule modules/dental_idr/procedure/d27.json
Loading submodule modules/dental_idr/procedure/d29.json
Loading submodule modules/dental_idr/procedure/d31.json
Loading submodule modules/dental_idr/procedure/d32.json
Loading submodule modules/dental_idr/procedure/d33.json
Loading submodule modules/dental_idr/procedure/d34.json
Loading submodule modules/dental_idr/procedure/d35.json

Loading submodule modules/dental_idr/procedure/d39.json
Loading submodule modules/dental_idr/procedure/d42.json
Loading submodule modules/dental_idr/procedure/d43.json
Loading submodule modules/dental_idr/procedure/d49.json
Loading submodule modules/dental_idr/procedure/d51.json
Loading submodule modules/dental_idr/procedure/d52.json
Loading submodule modules/dental_idr/procedure/d54.json
Loading submodule modules/dental_idr/procedure/d55.json
Loading submodule modules/dental_idr/procedure/d56.json
Loading submodule modules/dental_idr/procedure/d57.json
Loading submodule modules/dental_idr/procedure/d58.json
Loading submodule modules/dental_idr/procedure/d59.json
Loading submodule modules/dental_idr/procedure/d60.json
Loading submodule modules/dental_idr/procedure/d61.json

Loading submodule modules/dental_idr/procedure/d62.json
Loading submodule modules/dental_idr/procedure/d65.json
Loading submodule modules/dental_idr/procedure/d66.json
Loading submodule modules/dental_idr/procedure/d67.json
Loading submodule modules/dental_idr/procedure/d69.json
Loading submodule modules/dental_idr/procedure/d71.json
Loading submodule modules/dental_idr/procedure/d72.json
Loading submodule modules/dental_idr/procedure/d73.json
Loading submodule modules/dental_idr/procedure/d74.json
Loading submodule modules/dental_idr/procedure/d75.json
Loading submodule modules/dental_idr/procedure/d76.json
Loading submodule modules/dental_idr/procedure/d77.json
Loading submodule modules/dental_idr/procedure/d78.json
Loading submodule modules/dental_idr/procedure/d79.json

Loading submodule modules/dental_idr/procedure/d80.json
Loading submodule modules/dental_idr/procedure/d82.json
Loading submodule modules/dental_idr/procedure/d86.json
Loading submodule modules/dental_idr/procedure/d87.json
Loading submodule modules/dental_idr/procedure/d89.json
Loading submodule modules/dental_idr/procedure/d91.json
Loading submodule modules/dental_idr/procedure/d92.json
Loading submodule modules/dental_idr/procedure/d93.json
Loading submodule modules/dental_idr/procedure/d94.json
Loading submodule modules/dental_idr/procedure/d96.json
Loading submodule modules/dental_idr/procedure/d99.json
Loading submodule modules/dermatitis/early_moderate_eczema_obs.json
Loading submodule modules/dermatitis/early_severe_eczema_obs.json
Loading submodule modules/dermatitis/mid_moderate_eczema_obs.json
Loading submodule modules/dermatitis/mid_severe_eczema_obs.json
Loading submodule modules/dermatitis/moderate_cd_obs.json
Loading submodule modules/dermatitis/severe_cd_obs.json
Loading submodule modules/dme/wheelchair.json
Loading submodule modules/dme/wheelchair_end.json
Loading submodule modules/encounter/anxiety_screening.json
Loading submodule modules/encounter/depression_screening.json
Loading submodule modules/encounter/fall_risk_screening.json
Loading submodule modules/encounter/hark_screening.json
Loading submodule modules/encounter/hospital_basic_labs.json
Loading submodule modules/encounter/sdoh_hrsn.json

Loading submodule modules/encounter/substance_use_screening.json
Loading submodule modules/encounter/vitals.json
Loading submodule modules/eye/intraocular_pressure.json
Loading submodule modules/eye/ophthalmic_progression.json
Loading submodule modules/eye/ophthalmic_tomography.json
Loading submodule modules/eye/visual_acuity.json
Loading submodule modules/heart/acs_anticoagulant.json
Loading submodule modules/heart/acs_antiplatelet.json
Loading submodule modules/heart/acs_arrival_medications.json
Loading submodule modules/heart/acs_discharge_meds.json
Loading submodule modules/heart/avrr/antithrombotic.json
Loading submodule modules/heart/avrr/avrr_referral.json
Loading submodule modules/heart/avrr/intraop_meds_blood.json
Loading submodule modules/heart/avrr/outcomes.json
Loading submodule modules/heart/avrr/preoperative.json

Loading submodule modules/heart/avrr/savrr_operation.json
Loading submodule modules/heart/avrr/savrr_postop.json
Loading submodule modules/heart/avrr/sequence.json
Loading submodule modules/heart/cabg/cabg_referral.json
Loading submodule modules/heart/cabg/details.json
Loading Lookup Table: cabg_details_operative_approach.csv
Loading Lookup Table: cabg_details_num_grafts.csv
Loading Lookup Table: cabg_details_num_art_cond.csv
Loading submodule modules/heart/cabg/icu_meds_devices.json
Loading submodule modules/heart/cabg/labs_common.json
Loading submodule modules/heart/cabg/operation.json
Loading submodule modules/heart/cabg/or_intraop.json
Loading submodule modules/heart/cabg/or_labs_meds.json
Loading submodule modules/heart/cabg/outcomes.json

Loading submodule modules/heart/cabg/postop.json
Loading submodule modules/heart/cabg/postop_blood.json
Loading submodule modules/heart/cabg/preoperative.json
Loading submodule modules/heart/cabg_sequence.json
Loading submodule modules/heart/cardiac_labs.json
Loading submodule modules/heart/chf_lab_work.json
Loading submodule modules/heart/chf_lvad.json
Loading submodule modules/heart/chf_meds.json
Loading submodule modules/heart/chf_meds_hfmef.json
Loading submodule modules/heart/chf_meds_hfref_nyha2.json
Loading submodule modules/heart/chf_meds_hfref_nyha3.json
Loading submodule modules/heart/chf_meds_hfref_nyha4.json
Loading submodule modules/heart/chf_nyha_panel.json
Loading submodule modules/heart/chf_transplant.json

Loading submodule modules/heart/nsteacs_pathway.json
Loading submodule modules/heart/operative_status.json
Loading submodule modules/heart/or_blood.json
Loading Lookup Table: or_blood_anemia_check.csv
Loading Lookup Table: or_blood_platelet_check.csv
Loading Lookup Table: or_blood_plasma_check.csv
Loading submodule modules/heart/savrepair/operative_status.json
Loading submodule modules/heart/savreplace/operative_status.json
Loading submodule modules/heart/stemi_fibrinolytic.json
Loading submodule modules/heart/stemi_pathway.json
Loading submodule modules/heart/tavr/alt_access.json
Loading submodule modules/heart/tavr/operation.json
Loading submodule modules/heart/tavr/operative_status.json
Loading submodule modules/heart/tavr/outcomes.json
Loading submodule modules/heart/tavr/postop.json

Loading submodule modules/heart/vhd_risks.json
Loading submodule modules/hiv/art_sequence.json
Loading submodule modules/hiv/art_sequence_1987_1994.json
Loading submodule modules/hiv/art_sequence_1995_1996.json
Loading submodule modules/hiv/art_sequence_1997_2002.json
Loading submodule modules/hiv/art_sequence_2003_2005.json
Loading submodule modules/hiv/art_sequence_2006_2014.json
Loading submodule modules/hiv/art_sequence_2015.json
Loading submodule modules/hiv/hiv_baseline.json
Loading submodule modules/hiv/hiv_cd4.json
Loading Lookup Table: hiv_stage.csv

Loading submodule modules/hiv/hiv_oi_prophylaxis.json
Loading submodule modules/hiv/hiv_screening.json
Loading submodule modules/hiv/hiv_viral_load.json
Loading submodule modules/hiv/stop_all_art_meds.json
Loading submodule modules/injuries/broken_jaw.json
Loading submodule modules/lung_cancer/lung_cancer_probabilities.json
Loading submodule modules/medications/ace_arb.json
Loading Lookup Table: ace_arb_ingredient_distribution.csv
Loading Lookup Table: ace_arb_amlodipine_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: ace_arb_enalapril_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_irbesartan_product_distribution.csv
Loading Lookup Table: ace_arb_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_quinapril_product_distribution.csv
Loading Lookup Table: ace_arb_ramipril_product_distribution.csv
Loading Lookup Table: ace_arb_sacubitril_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_telmisartan_product_distribution.csv
Loading Lookup Table: ace_arb_valsartan_product_distribution.csv

Loading submodule modules/medications/beta_blocker.json
Loading Lookup Table: beta_blocker_ingredient_distribution.csv
Loading Lookup Table: beta_blocker_atenolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: beta_blocker_carvedilol_product_distribution.csv
Loading Lookup Table: beta_blocker_labetalol_product_distribution.csv
Loading Lookup Table: beta_blocker_metoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_nebivolol_product_distribution.csv
Loading Lookup Table: beta_blocker_propranolol_product_distribution.csv
Loading submodule modules/medications/ear_infection_antibiotic.json
Loading submodule modules/medications/emergency_inhaler.json
Loading Lookup Table: emergency_inhaler_ingredient_distribution.csv
Loading Lookup Table: emergency_inhaler_albuterol_product_distribution.csv
Loading Lookup Table: emergency_inhaler_levalbuterol_product_distribution.csv
Loading submodule modules/medications/hypertension_medication.json
Loading submodule modules/medications/maintenance_inhaler.json
Loading Lookup Table: maintenance_inhaler_ingredient_distribution.csv
Loading Lookup Table: maintenance_inhaler_beclomethasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_budesonide_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_fluticasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_mometasone_product_distribution.csv
Loading submodule modules/medications/moderate_opioid_pain_reliever.json
Loading submodule modules/medications/otc_antihistamine.json
Loading submodule modules/medications/otc_pain_reliever.json
Loading submodule modules/medications/statin.json
Loading Lookup Table: statin_ingredient_distribution.csv
Loading Lookup Table: statin_atorvastatin_product_distribution.csv
Loading Lookup Table: statin_ezetimibe_simvastatin_product_distribution.csv
Loading Lookup Table: statin_lovastatin_product_distribution.csv
Loading Lookup Table: statin_pitavastatin_product_distribution.csv

Loading Lookup Table: statin_pravastatin_product_distribution.csv
Loading Lookup Table: statin_rosuvastatin_product_distribution.csv
Loading Lookup Table: statin_simvastatin_product_distribution.csv
Loading submodule modules/medications/strong_opioid_pain_reliever.json
Loading submodule modules/metabolic_syndrome/amputations.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_diagnoses.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_progression.json
Loading submodule modules/metabolic_syndrome/dme_supplies.json
Loading submodule modules/metabolic_syndrome/kidney_conditions.json
Loading submodule modules/metabolic_syndrome/medications.json
Loading submodule modules/snf/skilled_nursing_facility.json
Loading submodule modules/surgery/general_anesthesia.json
Loading submodule modules/total_joint_replacement/functional_status_assessments.json
Loading submodule modules/uti/abx_tx.json

Loading submodule modules/uti/ambulatory_eval.json
Loading submodule modules/uti/ambulatory_path.json
Loading submodule modules/uti/ed_bundle.json
Loading submodule modules/uti/ed_eval.json
Loading submodule modules/uti/ed_path.json
Loading submodule modules/uti/gu_pregnancy_check.json
Loading submodule modules/uti/hpi.json
Loading submodule modules/uti/lab_follow_up.json
Loading submodule modules/uti/labs.json
Loading submodule modules/uti/telemed_path.json
Loading submodule modules/veterans/veteran_suicide_probabilities.json
Loading submodule modules/weight_loss/mend_week.json
Loading module modules/AIS_From_School_Screening_to_SOSORT_Recommendations.json

Loading module modules/acute_myeloid_leukemia.json
Loading Lookup Table: AML.csv
Loading module modules/allergic_rhinitis.json
Loading module modules/allergies.json
Loading module modules/anemia___unknown_etiology.json
Loading module modules/appendicitis.json
Loading module modules/asthma.json
Loading module modules/atopy.json
Loading module modules/atrial_fibrillation.json
Loading module modules/attention_deficit_disorder.json

Loading module modules/bone_marrow_transplant.json
Loading module modules/breast_cancer.json
Loading module modules/bronchitis.json
Loading module modules/cerebral_palsy.json

Loading module modules/chronic_kidney_disease.json
Loading module modules/colorectal_cancer.json
Loading module modules/congestive_heart_failure.json

Loading module modules/contraceptive_maintenance.json
Loading module modules/contraceptives.json
Loading module modules/copd.json
Loading module modules/covid19.json
Loading Lookup Table: covid19_prob.csv
Loading module modules/cystic_fibrosis.json
Loading module modules/dementia.json
Loading module modules/dental_and_oral_examination.json

Loading module modules/dental_encounters.json
Loading module modules/dental_medicare_clustered_encounters.json
Loading module modules/dentures.json
Loading module modules/dermatitis.json
Loading module modules/diabetic_retinopathy_treatment.json
Loading Lookup Table: diabetic_retinopathy_followup.csv
Loading module modules/dialysis.json
Loading module modules/ear_infections.json
Loading module modules/epilepsy.json
Loading module modules/female_reproduction.json
Loading module modules/fibromyalgia.json

Loading module modules/food_allergies.json
Loading module modules/gallstones.json
Loading module modules/gout.json
Loading module modules/hiv_care.json
Loading Lookup Table: hiv_care.csv
Loading module modules/hiv_diagnosis.json
Loading Lookup Table: hiv_mortality_later.csv
Loading Lookup Table: hiv_mortality_early.csv
Loading Lookup Table: hiv_mortality_very_early.csv
Loading Lookup Table: hiv_diagnosis_early.csv
Loading Lookup Table: hiv_diagnosis_later.csv
Loading module modules/home_health_treatment.json
Loading module modules/home_hospice_snf.json

Loading module modules/homelessness.json
Loading module modules/hospice_treatment.json
Loading module modules/hypertension.json
Loading module modules/hypothyroidism.json
Loading module modules/injuries.json

Loading module modules/kidney_transplant.json
Loading module modules/lung_cancer.json
Loading module modules/lupus.json
Loading module modules/mTBI.json
Loading module modules/med_rec.json
Loading module modules/mend_program.json
Loading module modules/metabolic_syndrome_care.json
Loading module modules/metabolic_syndrome_disease.json

Loading module modules/myocardial_infarction.json
Loading module modules/opioid_addiction.json
Loading module modules/osteoarthritis.json
Loading module modules/osteoporosis.json
Loading module modules/pregnancy.json
Loading module modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json

Loading module modules/rheumatoid_arthritis.json
Loading module modules/self_harm.json
Loading module modules/sepsis.json
Loading module modules/sexual_activity.json
Loading module modules/sinusitis.json
Loading module modules/sleep_apnea.json
Loading module modules/sore_throat.json
Loading module modules/spina_bifida.json
Loading module modules/stable_ischemic_heart_disease.json

Loading module modules/stroke.json
Loading module modules/total_joint_replacement.json
Loading module modules/trigger_bone_marrow_transplant.json
Loading module modules/urinary_tract_infections.json
Loading Lookup Table: uti.csv
Loading Lookup Table: uti_recurrence.csv
Loading module modules/veteran.json
Loading module modules/veteran_hyperlipidemia.json
Loading module modules/veteran_lung_cancer.json
Loading module modules/veteran_mdd.json
Loading module modules/veteran_prostate_cancer.json
Loading module modules/veteran_ptsd.json

Loading module modules/veteran_self_harm.json
Loading module modules/veteran_substance_abuse_conditions.json
Loading module modules/veteran_substance_abuse_treatment.json
Loading module modules/vhd_aortic.json
Loading Lookup Table: vhd_as.csv
Loading Lookup Table: vhd_ar.csv
Loading module modules/vhd_mitral.json
Loading Lookup Table: vhd_mr.csv
Loading Lookup Table: vhd_ms.csv
Loading module modules/vhd_pulmonic.json
Loading Lookup Table: vhd_ps.csv
Loading Lookup Table: vhd_pr.csv
Loading module modules/vhd_tricuspid.json
Loading Lookup Table: vhd_tr.csv
Loading Lookup Table: vhd_ts.csv
Loading module modules/wellness_encounters.json
Running with options:
Population: 3
Seed: 7
Provider Seed:1791484082286
Reference Time: 1791484082286
Location: Massachusetts
Min Age: 0
Max Age: 140

1 -- Darron84 Hegmann834 (36 y/o M) Salem, Massachusetts  (50652)

2 -- Samara159 Runolfsdottir785 (14 y/o F) Chelsea, Massachusetts  (20570)
3 -- Gwyn381 Runolfsson901 (22 y/o F) North Attleborough, Massachusetts  (31764)

Records: total=3, alive=3, dead=0
RNG=3
Clinician RNG=5640

You've just generated 3 patients! We're happy to know Synthea is helping you with your project.
Like what we're doing? Synthea is an open-source project, and your support helps us keep building.
Please consider ]8;;https://github.com/sponsors/synthetichealthmaking a donation]8;; (https://github.com/sponsors/synthetichealth).

['allergies.csv',
 'careplans.csv',
 'claims.csv',
 'claims_transactions.csv',
 'conditions.csv',
 'devices.csv',
 'encounters.csv',
 'imaging_studies.csv',
 'immunizations.csv',
 'medications.csv',
 'observations.csv',
 'organizations.csv',
 'patients.csv',
 'payer_transitions.csv',
 'payers.csv',
 'procedures.csv',
 'providers.csv',
 'supplies.csv']

Calling `generate()` again with identical settings returns the existing directory immediately instead of rerunning Synthea. `overwrite=True` forces a fresh run into the same directory. If `seed` is omitted, a random seed is chosen and logged, so each seedless call is a new population.

In [8]:
reused_path = synthea.generate(**settings)
assert reused_path == csv_path

overwritten_path = synthea.generate(**settings, overwrite=True)
assert overwritten_path == csv_path

Reusing existing Synthea output at /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv

Running Synthea: /home/soham/.local/jvm/jdk-17.0.20.1+1/bin/java -jar /home/soham/.cache/pyhealth/synthea/synthea-with-dependencies-v4.0.0.jar --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --exporter.years_of_history=5 --generate.only_alive_patients=true --generate.thread_pool_size=1 -s 42 -cs 43 -p 10 -r 20240101 -g F -a 30-40 -o false Massachusetts Boston

org.mitre.synthea.X12.ExporterAdaptor
org.mitre.synthea.X12.ExporterAdaptor

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

Scanned 92 modules and 449 submodules.
Loading submodule modules/allergies/allergy_panel.json
Loading submodule modules/allergies/drug_allergy_incidence.json

Loading submodule modules/allergies/environmental_allergy_incidence.json
Loading submodule modules/allergies/food_allergy_incidence.json
Loading submodule modules/allergies/immunotherapy.json
Loading submodule modules/allergies/outgrow_env_allergies.json
Loading submodule modules/allergies/outgrow_food_allergies.json
Loading submodule modules/allergies/severe_allergic_reaction.json
Loading submodule modules/anemia/anemia_sub.json
Loading submodule modules/breast_cancer/chemotherapy_breast.json
Loading submodule modules/breast_cancer/hormone_diagnosis.json

Loading submodule modules/breast_cancer/hormonetherapy_breast.json
Loading submodule modules/breast_cancer/surgery_therapy_breast.json
Loading submodule modules/breast_cancer/tnm_diagnosis.json
Loading submodule modules/contraceptives/clear_contraceptive.json
Loading submodule modules/contraceptives/female_sterilization.json
Loading submodule modules/contraceptives/implant_contraceptive.json
Loading submodule modules/contraceptives/injectable_contraceptive.json
Loading submodule modules/contraceptives/intrauterine_device.json
Loading submodule modules/contraceptives/male_sterilization.json
Loading submodule modules/contraceptives/oral_contraceptive.json
Loading submodule modules/contraceptives/patch_contraceptive.json
Loading submodule modules/contraceptives/ring_contraceptive.json
Loading submodule modules/covid19/admission.json

Loading submodule modules/covid19/determine_risk.json
Loading Lookup Table: covid-19-severity-outcomes.csv
Loading Lookup Table: covid-19-survival-outcomes.csv
Loading submodule modules/covid19/diagnose_bacterial_infection.json
Loading submodule modules/covid19/diagnose_blood_clot.json
Loading submodule modules/covid19/end_outcomes.json
Loading submodule modules/covid19/end_symptoms.json
Loading submodule modules/covid19/infection.json
Loading submodule modules/covid19/measurements_daily.json
Loading submodule modules/covid19/measurements_frequent.json
Loading submodule modules/covid19/measurements_vitals.json
Loading submodule modules/covid19/medications.json
Loading submodule modules/covid19/nonsurvivor_lab_values.json
Loading submodule modules/covid19/outcomes.json
Loading submodule modules/covid19/supplies_hospitalization.json
Loading submodule modules/covid19/supplies_icu.json
Loading submodule modules/covid19/supplies_intubation.json
Loading submodule modules/covid19/survivor_lab_values.json

Loading submodule modules/covid19/symptoms.json
Loading submodule modules/covid19/treat_blood_clot.json
Loading submodule modules/dental/dental_emergency.json
Loading submodule modules/dental/dental_encounter.json
Loading submodule modules/dental/dental_hospital.json
Loading submodule modules/dental/dental_telephone.json
Loading submodule modules/dental/diagnosis/cavity.json
Loading submodule modules/dental/diagnosis/dental disorder.json

Loading submodule modules/dental/diagnosis/gingivitis.json
Loading submodule modules/dental/diagnosis/periodontitis.json
Loading submodule modules/dental/diagnosis/plaque.json
Loading submodule modules/dental/end_dental_diagnoses.json
Loading submodule modules/dental/procedure/d01.json
Loading submodule modules/dental/procedure/d02.json
Loading submodule modules/dental/procedure/d03.json
Loading submodule modules/dental/procedure/d04.json
Loading submodule modules/dental/procedure/d05.json
Loading submodule modules/dental/procedure/d06.json
Loading submodule modules/dental/procedure/d09.json
Loading submodule modules/dental/procedure/d11.json
Loading submodule modules/dental/procedure/d12.json
Loading submodule modules/dental/procedure/d13.json
Loading submodule modules/dental/procedure/d15.json
Loading submodule modules/dental/procedure/d19.json
Loading submodule modules/dental/procedure/d21.json
Loading submodule modules/dental/procedure/d23.json
Loading submodule modules/dental/procedure/d25.json
Loading submodule modules/dental/procedure/d26.json
Loading submodule modules/dental/procedure/d27.json
Loading submodule modules/dental/procedure/d29.json

Loading submodule modules/dental/procedure/d31.json
Loading submodule modules/dental/procedure/d32.json
Loading submodule modules/dental/procedure/d33.json
Loading submodule modules/dental/procedure/d34.json
Loading submodule modules/dental/procedure/d39.json
Loading submodule modules/dental/procedure/d42.json
Loading submodule modules/dental/procedure/d43.json
Loading submodule modules/dental/procedure/d49.json
Loading submodule modules/dental/procedure/d51.json
Loading submodule modules/dental/procedure/d52.json
Loading submodule modules/dental/procedure/d54.json
Loading submodule modules/dental/procedure/d55.json
Loading submodule modules/dental/procedure/d56.json
Loading submodule modules/dental/procedure/d57.json
Loading submodule modules/dental/procedure/d58.json
Loading submodule modules/dental/procedure/d59.json
Loading submodule modules/dental/procedure/d60.json
Loading submodule modules/dental/procedure/d61.json
Loading submodule modules/dental/procedure/d62.json
Loading submodule modules/dental/procedure/d65.json
Loading submodule modules/dental/procedure/d66.json
Loading submodule modules/dental/procedure/d67.json

Loading submodule modules/dental/procedure/d69.json
Loading submodule modules/dental/procedure/d71.json
Loading submodule modules/dental/procedure/d72.json
Loading submodule modules/dental/procedure/d73.json
Loading submodule modules/dental/procedure/d74.json
Loading submodule modules/dental/procedure/d75.json
Loading submodule modules/dental/procedure/d76.json
Loading submodule modules/dental/procedure/d77.json
Loading submodule modules/dental/procedure/d78.json
Loading submodule modules/dental/procedure/d79.json
Loading submodule modules/dental/procedure/d80.json
Loading submodule modules/dental/procedure/d82.json
Loading submodule modules/dental/procedure/d86.json
Loading submodule modules/dental/procedure/d89.json
Loading submodule modules/dental/procedure/d91.json
Loading submodule modules/dental/procedure/d92.json
Loading submodule modules/dental/procedure/d93.json
Loading submodule modules/dental/procedure/d94.json
Loading submodule modules/dental/procedure/d96.json
Loading submodule modules/dental/procedure/d99.json
Loading submodule modules/dental_idr/dental_idr_cluster_0.json

Loading submodule modules/dental_idr/dental_idr_cluster_1.json
Loading submodule modules/dental_idr/dental_idr_cluster_2.json
Loading submodule modules/dental_idr/dental_idr_cluster_3.json

Loading submodule modules/dental_idr/dental_idr_cluster_4.json
Loading submodule modules/dental_idr/diagnosis/c00.json
Loading submodule modules/dental_idr/diagnosis/c01.json
Loading submodule modules/dental_idr/diagnosis/c02.json
Loading submodule modules/dental_idr/diagnosis/c03.json
Loading submodule modules/dental_idr/diagnosis/c04.json
Loading submodule modules/dental_idr/diagnosis/c05.json
Loading submodule modules/dental_idr/diagnosis/c06.json

Loading submodule modules/dental_idr/diagnosis/c07.json
Loading submodule modules/dental_idr/diagnosis/c08.json
Loading submodule modules/dental_idr/diagnosis/c09.json
Loading submodule modules/dental_idr/diagnosis/c10.json
Loading submodule modules/dental_idr/diagnosis/c11.json
Loading submodule modules/dental_idr/diagnosis/c12.json
Loading submodule modules/dental_idr/diagnosis/c13.json
Loading submodule modules/dental_idr/diagnosis/c14.json
Loading submodule modules/dental_idr/diagnosis/c15.json
Loading submodule modules/dental_idr/diagnosis/c16.json
Loading submodule modules/dental_idr/diagnosis/c17.json
Loading submodule modules/dental_idr/diagnosis/c18.json
Loading submodule modules/dental_idr/diagnosis/c19.json
Loading submodule modules/dental_idr/diagnosis/c20.json
Loading submodule modules/dental_idr/diagnosis/c21.json
Loading submodule modules/dental_idr/diagnosis/c22.json
Loading submodule modules/dental_idr/diagnosis/c24.json
Loading submodule modules/dental_idr/diagnosis/c25.json
Loading submodule modules/dental_idr/diagnosis/c26.json
Loading submodule modules/dental_idr/diagnosis/c30.json
Loading submodule modules/dental_idr/diagnosis/c31.json
Loading submodule modules/dental_idr/diagnosis/c32.json
Loading submodule modules/dental_idr/diagnosis/c33.json
Loading submodule modules/dental_idr/diagnosis/c34.json
Loading submodule modules/dental_idr/diagnosis/c37.json
Loading submodule modules/dental_idr/diagnosis/c38.json
Loading submodule modules/dental_idr/diagnosis/c39.json
Loading submodule modules/dental_idr/diagnosis/c40.json
Loading submodule modules/dental_idr/diagnosis/c41.json
Loading submodule modules/dental_idr/diagnosis/c43.json
Loading submodule modules/dental_idr/diagnosis/c44.json
Loading submodule modules/dental_idr/diagnosis/c45.json
Loading submodule modules/dental_idr/diagnosis/c46.json
Loading submodule modules/dental_idr/diagnosis/c47.json
Loading submodule modules/dental_idr/diagnosis/c48.json
Loading submodule modules/dental_idr/diagnosis/c49.json
Loading submodule modules/dental_idr/diagnosis/c4a.json
Loading submodule modules/dental_idr/diagnosis/c50.json

Loading submodule modules/dental_idr/diagnosis/c51.json
Loading submodule modules/dental_idr/diagnosis/c53.json
Loading submodule modules/dental_idr/diagnosis/c54.json
Loading submodule modules/dental_idr/diagnosis/c56.json
Loading submodule modules/dental_idr/diagnosis/c57.json
Loading submodule modules/dental_idr/diagnosis/c61.json
Loading submodule modules/dental_idr/diagnosis/c62.json
Loading submodule modules/dental_idr/diagnosis/c63.json
Loading submodule modules/dental_idr/diagnosis/c64.json
Loading submodule modules/dental_idr/diagnosis/c65.json
Loading submodule modules/dental_idr/diagnosis/c66.json
Loading submodule modules/dental_idr/diagnosis/c67.json
Loading submodule modules/dental_idr/diagnosis/c68.json
Loading submodule modules/dental_idr/diagnosis/c69.json
Loading submodule modules/dental_idr/diagnosis/c71.json
Loading submodule modules/dental_idr/diagnosis/c72.json
Loading submodule modules/dental_idr/diagnosis/c73.json
Loading submodule modules/dental_idr/diagnosis/c74.json
Loading submodule modules/dental_idr/diagnosis/c75.json
Loading submodule modules/dental_idr/diagnosis/c76.json
Loading submodule modules/dental_idr/diagnosis/c77.json
Loading submodule modules/dental_idr/diagnosis/c78.json
Loading submodule modules/dental_idr/diagnosis/c79.json
Loading submodule modules/dental_idr/diagnosis/c7a.json
Loading submodule modules/dental_idr/diagnosis/c7b.json
Loading submodule modules/dental_idr/diagnosis/c80.json
Loading submodule modules/dental_idr/diagnosis/c81.json
Loading submodule modules/dental_idr/diagnosis/c82.json
Loading submodule modules/dental_idr/diagnosis/c83.json
Loading submodule modules/dental_idr/diagnosis/c84.json
Loading submodule modules/dental_idr/diagnosis/c85.json
Loading submodule modules/dental_idr/diagnosis/c86.json
Loading submodule modules/dental_idr/diagnosis/c88.json
Loading submodule modules/dental_idr/diagnosis/c90.json

Loading submodule modules/dental_idr/diagnosis/c91.json
Loading submodule modules/dental_idr/diagnosis/c92.json
Loading submodule modules/dental_idr/diagnosis/c93.json
Loading submodule modules/dental_idr/diagnosis/c95.json
Loading submodule modules/dental_idr/diagnosis/c96.json
Loading submodule modules/dental_idr/diagnosis/d00.json
Loading submodule modules/dental_idr/diagnosis/d01.json
Loading submodule modules/dental_idr/diagnosis/d02.json
Loading submodule modules/dental_idr/diagnosis/d03.json
Loading submodule modules/dental_idr/diagnosis/d04.json
Loading submodule modules/dental_idr/diagnosis/d05.json
Loading submodule modules/dental_idr/diagnosis/d06.json
Loading submodule modules/dental_idr/diagnosis/d07.json
Loading submodule modules/dental_idr/diagnosis/d09.json
Loading submodule modules/dental_idr/diagnosis/d10.json
Loading submodule modules/dental_idr/diagnosis/d11.json
Loading submodule modules/dental_idr/diagnosis/d12.json
Loading submodule modules/dental_idr/diagnosis/d13.json
Loading submodule modules/dental_idr/diagnosis/d14.json
Loading submodule modules/dental_idr/diagnosis/d16.json
Loading submodule modules/dental_idr/diagnosis/d17.json
Loading submodule modules/dental_idr/diagnosis/d18.json
Loading submodule modules/dental_idr/diagnosis/d19.json
Loading submodule modules/dental_idr/diagnosis/d21.json
Loading submodule modules/dental_idr/diagnosis/d22.json
Loading submodule modules/dental_idr/diagnosis/d23.json
Loading submodule modules/dental_idr/diagnosis/d24.json
Loading submodule modules/dental_idr/diagnosis/d25.json
Loading submodule modules/dental_idr/diagnosis/d28.json
Loading submodule modules/dental_idr/diagnosis/d29.json
Loading submodule modules/dental_idr/diagnosis/d30.json
Loading submodule modules/dental_idr/diagnosis/d31.json

Loading submodule modules/dental_idr/diagnosis/d32.json
Loading submodule modules/dental_idr/diagnosis/d33.json
Loading submodule modules/dental_idr/diagnosis/d34.json
Loading submodule modules/dental_idr/diagnosis/d35.json
Loading submodule modules/dental_idr/diagnosis/d36.json
Loading submodule modules/dental_idr/diagnosis/d37.json
Loading submodule modules/dental_idr/diagnosis/d38.json
Loading submodule modules/dental_idr/diagnosis/d39.json
Loading submodule modules/dental_idr/diagnosis/d3a.json
Loading submodule modules/dental_idr/diagnosis/d40.json
Loading submodule modules/dental_idr/diagnosis/d41.json
Loading submodule modules/dental_idr/diagnosis/d44.json
Loading submodule modules/dental_idr/diagnosis/d45.json
Loading submodule modules/dental_idr/diagnosis/d46.json
Loading submodule modules/dental_idr/diagnosis/d47.json
Loading submodule modules/dental_idr/diagnosis/d48.json
Loading submodule modules/dental_idr/diagnosis/d49.json
Loading submodule modules/dental_idr/diagnosis/k00.json
Loading submodule modules/dental_idr/diagnosis/k01.json
Loading submodule modules/dental_idr/diagnosis/k02.json
Loading submodule modules/dental_idr/diagnosis/k03.json
Loading submodule modules/dental_idr/diagnosis/k04.json
Loading submodule modules/dental_idr/diagnosis/k05.json
Loading submodule modules/dental_idr/diagnosis/k06.json
Loading submodule modules/dental_idr/diagnosis/k08.json

Loading submodule modules/dental_idr/diagnosis/k09.json
Loading submodule modules/dental_idr/diagnosis/k11.json
Loading submodule modules/dental_idr/diagnosis/k12.json
Loading submodule modules/dental_idr/diagnosis/k13.json
Loading submodule modules/dental_idr/diagnosis/m26.json
Loading submodule modules/dental_idr/diagnosis/m27.json
Loading submodule modules/dental_idr/diagnosis/r69.json
Loading submodule modules/dental_idr/diagnosis/s02.json

Loading submodule modules/dental_idr/diagnosis/z00.json
Loading submodule modules/dental_idr/diagnosis/z01.json
Loading submodule modules/dental_idr/diagnosis/z13.json
Loading submodule modules/dental_idr/diagnosis/z40.json
Loading submodule modules/dental_idr/diagnosis/z41.json
Loading submodule modules/dental_idr/diagnosis/z51.json
Loading submodule modules/dental_idr/end_dental_diagnoses.json
Loading submodule modules/dental_idr/procedure/d01.json
Loading submodule modules/dental_idr/procedure/d02.json

Loading submodule modules/dental_idr/procedure/d03.json
Loading submodule modules/dental_idr/procedure/d04.json
Loading submodule modules/dental_idr/procedure/d05.json
Loading submodule modules/dental_idr/procedure/d06.json
Loading submodule modules/dental_idr/procedure/d07.json
Loading submodule modules/dental_idr/procedure/d08.json
Loading submodule modules/dental_idr/procedure/d09.json
Loading submodule modules/dental_idr/procedure/d11.json
Loading submodule modules/dental_idr/procedure/d12.json
Loading submodule modules/dental_idr/procedure/d13.json
Loading submodule modules/dental_idr/procedure/d15.json
Loading submodule modules/dental_idr/procedure/d17.json
Loading submodule modules/dental_idr/procedure/d19.json
Loading submodule modules/dental_idr/procedure/d21.json
Loading submodule modules/dental_idr/procedure/d23.json
Loading submodule modules/dental_idr/procedure/d24.json
Loading submodule modules/dental_idr/procedure/d25.json
Loading submodule modules/dental_idr/procedure/d26.json
Loading submodule modules/dental_idr/procedure/d27.json
Loading submodule modules/dental_idr/procedure/d29.json

Loading submodule modules/dental_idr/procedure/d31.json
Loading submodule modules/dental_idr/procedure/d32.json
Loading submodule modules/dental_idr/procedure/d33.json
Loading submodule modules/dental_idr/procedure/d34.json
Loading submodule modules/dental_idr/procedure/d35.json
Loading submodule modules/dental_idr/procedure/d39.json
Loading submodule modules/dental_idr/procedure/d42.json
Loading submodule modules/dental_idr/procedure/d43.json
Loading submodule modules/dental_idr/procedure/d49.json
Loading submodule modules/dental_idr/procedure/d51.json
Loading submodule modules/dental_idr/procedure/d52.json
Loading submodule modules/dental_idr/procedure/d54.json
Loading submodule modules/dental_idr/procedure/d55.json
Loading submodule modules/dental_idr/procedure/d56.json
Loading submodule modules/dental_idr/procedure/d57.json
Loading submodule modules/dental_idr/procedure/d58.json
Loading submodule modules/dental_idr/procedure/d59.json

Loading submodule modules/dental_idr/procedure/d60.json
Loading submodule modules/dental_idr/procedure/d61.json
Loading submodule modules/dental_idr/procedure/d62.json
Loading submodule modules/dental_idr/procedure/d65.json
Loading submodule modules/dental_idr/procedure/d66.json
Loading submodule modules/dental_idr/procedure/d67.json
Loading submodule modules/dental_idr/procedure/d69.json
Loading submodule modules/dental_idr/procedure/d71.json
Loading submodule modules/dental_idr/procedure/d72.json
Loading submodule modules/dental_idr/procedure/d73.json
Loading submodule modules/dental_idr/procedure/d74.json
Loading submodule modules/dental_idr/procedure/d75.json
Loading submodule modules/dental_idr/procedure/d76.json
Loading submodule modules/dental_idr/procedure/d77.json

Loading submodule modules/dental_idr/procedure/d78.json
Loading submodule modules/dental_idr/procedure/d79.json
Loading submodule modules/dental_idr/procedure/d80.json
Loading submodule modules/dental_idr/procedure/d82.json
Loading submodule modules/dental_idr/procedure/d86.json
Loading submodule modules/dental_idr/procedure/d87.json
Loading submodule modules/dental_idr/procedure/d89.json
Loading submodule modules/dental_idr/procedure/d91.json
Loading submodule modules/dental_idr/procedure/d92.json
Loading submodule modules/dental_idr/procedure/d93.json
Loading submodule modules/dental_idr/procedure/d94.json
Loading submodule modules/dental_idr/procedure/d96.json
Loading submodule modules/dental_idr/procedure/d99.json
Loading submodule modules/dermatitis/early_moderate_eczema_obs.json
Loading submodule modules/dermatitis/early_severe_eczema_obs.json
Loading submodule modules/dermatitis/mid_moderate_eczema_obs.json
Loading submodule modules/dermatitis/mid_severe_eczema_obs.json
Loading submodule modules/dermatitis/moderate_cd_obs.json
Loading submodule modules/dermatitis/severe_cd_obs.json
Loading submodule modules/dme/wheelchair.json
Loading submodule modules/dme/wheelchair_end.json
Loading submodule modules/encounter/anxiety_screening.json

Loading submodule modules/encounter/depression_screening.json
Loading submodule modules/encounter/fall_risk_screening.json
Loading submodule modules/encounter/hark_screening.json
Loading submodule modules/encounter/hospital_basic_labs.json
Loading submodule modules/encounter/sdoh_hrsn.json
Loading submodule modules/encounter/substance_use_screening.json

Loading submodule modules/encounter/vitals.json
Loading submodule modules/eye/intraocular_pressure.json
Loading submodule modules/eye/ophthalmic_progression.json
Loading submodule modules/eye/ophthalmic_tomography.json
Loading submodule modules/eye/visual_acuity.json
Loading submodule modules/heart/acs_anticoagulant.json
Loading submodule modules/heart/acs_antiplatelet.json
Loading submodule modules/heart/acs_arrival_medications.json
Loading submodule modules/heart/acs_discharge_meds.json
Loading submodule modules/heart/avrr/antithrombotic.json
Loading submodule modules/heart/avrr/avrr_referral.json
Loading submodule modules/heart/avrr/intraop_meds_blood.json
Loading submodule modules/heart/avrr/outcomes.json
Loading submodule modules/heart/avrr/preoperative.json
Loading submodule modules/heart/avrr/savrr_operation.json

Loading submodule modules/heart/avrr/savrr_postop.json
Loading submodule modules/heart/avrr/sequence.json
Loading submodule modules/heart/cabg/cabg_referral.json
Loading submodule modules/heart/cabg/details.json
Loading Lookup Table: cabg_details_operative_approach.csv
Loading Lookup Table: cabg_details_num_grafts.csv
Loading Lookup Table: cabg_details_num_art_cond.csv
Loading submodule modules/heart/cabg/icu_meds_devices.json
Loading submodule modules/heart/cabg/labs_common.json
Loading submodule modules/heart/cabg/operation.json
Loading submodule modules/heart/cabg/or_intraop.json
Loading submodule modules/heart/cabg/or_labs_meds.json
Loading submodule modules/heart/cabg/outcomes.json
Loading submodule modules/heart/cabg/postop.json

Loading submodule modules/heart/cabg/postop_blood.json
Loading submodule modules/heart/cabg/preoperative.json
Loading submodule modules/heart/cabg_sequence.json
Loading submodule modules/heart/cardiac_labs.json
Loading submodule modules/heart/chf_lab_work.json
Loading submodule modules/heart/chf_lvad.json
Loading submodule modules/heart/chf_meds.json
Loading submodule modules/heart/chf_meds_hfmef.json
Loading submodule modules/heart/chf_meds_hfref_nyha2.json
Loading submodule modules/heart/chf_meds_hfref_nyha3.json
Loading submodule modules/heart/chf_meds_hfref_nyha4.json
Loading submodule modules/heart/chf_nyha_panel.json
Loading submodule modules/heart/chf_transplant.json
Loading submodule modules/heart/nsteacs_pathway.json

Loading submodule modules/heart/operative_status.json
Loading submodule modules/heart/or_blood.json
Loading Lookup Table: or_blood_anemia_check.csv
Loading Lookup Table: or_blood_platelet_check.csv
Loading Lookup Table: or_blood_plasma_check.csv
Loading submodule modules/heart/savrepair/operative_status.json
Loading submodule modules/heart/savreplace/operative_status.json
Loading submodule modules/heart/stemi_fibrinolytic.json
Loading submodule modules/heart/stemi_pathway.json
Loading submodule modules/heart/tavr/alt_access.json
Loading submodule modules/heart/tavr/operation.json
Loading submodule modules/heart/tavr/operative_status.json
Loading submodule modules/heart/tavr/outcomes.json
Loading submodule modules/heart/tavr/postop.json
Loading submodule modules/heart/vhd_risks.json
Loading submodule modules/hiv/art_sequence.json
Loading submodule modules/hiv/art_sequence_1987_1994.json

Loading submodule modules/hiv/art_sequence_1995_1996.json
Loading submodule modules/hiv/art_sequence_1997_2002.json
Loading submodule modules/hiv/art_sequence_2003_2005.json
Loading submodule modules/hiv/art_sequence_2006_2014.json
Loading submodule modules/hiv/art_sequence_2015.json
Loading submodule modules/hiv/hiv_baseline.json
Loading submodule modules/hiv/hiv_cd4.json
Loading Lookup Table: hiv_stage.csv
Loading submodule modules/hiv/hiv_oi_prophylaxis.json

Loading submodule modules/hiv/hiv_screening.json
Loading submodule modules/hiv/hiv_viral_load.json
Loading submodule modules/hiv/stop_all_art_meds.json
Loading submodule modules/injuries/broken_jaw.json
Loading submodule modules/lung_cancer/lung_cancer_probabilities.json
Loading submodule modules/medications/ace_arb.json
Loading Lookup Table: ace_arb_ingredient_distribution.csv
Loading Lookup Table: ace_arb_amlodipine_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_product_distribution.csv
Loading Lookup Table: ace_arb_benazepril_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: ace_arb_enalapril_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_hydrochlorothiazide_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_irbesartan_product_distribution.csv
Loading Lookup Table: ace_arb_lisinopril_product_distribution.csv
Loading Lookup Table: ace_arb_losartan_product_distribution.csv
Loading Lookup Table: ace_arb_quinapril_product_distribution.csv
Loading Lookup Table: ace_arb_ramipril_product_distribution.csv
Loading Lookup Table: ace_arb_sacubitril_valsartan_product_distribution.csv
Loading Lookup Table: ace_arb_telmisartan_product_distribution.csv
Loading Lookup Table: ace_arb_valsartan_product_distribution.csv

Loading submodule modules/medications/beta_blocker.json
Loading Lookup Table: beta_blocker_ingredient_distribution.csv
Loading Lookup Table: beta_blocker_atenolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_bisoprolol_hydrochlorothiazide_product_distribution.csv
Loading Lookup Table: beta_blocker_carvedilol_product_distribution.csv
Loading Lookup Table: beta_blocker_labetalol_product_distribution.csv
Loading Lookup Table: beta_blocker_metoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_nebivolol_product_distribution.csv
Loading Lookup Table: beta_blocker_propranolol_product_distribution.csv
Loading submodule modules/medications/ear_infection_antibiotic.json
Loading submodule modules/medications/emergency_inhaler.json
Loading Lookup Table: emergency_inhaler_ingredient_distribution.csv
Loading Lookup Table: emergency_inhaler_albuterol_product_distribution.csv
Loading Lookup Table: emergency_inhaler_levalbuterol_product_distribution.csv
Loading submodule modules/medications/hypertension_medication.json
Loading submodule modules/medications/maintenance_inhaler.json
Loading Lookup Table: maintenance_inhaler_ingredient_distribution.csv
Loading Lookup Table: maintenance_inhaler_beclomethasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_budesonide_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_fluticasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_mometasone_product_distribution.csv
Loading submodule modules/medications/moderate_opioid_pain_reliever.json
Loading submodule modules/medications/otc_antihistamine.json
Loading submodule modules/medications/otc_pain_reliever.json
Loading submodule modules/medications/statin.json
Loading Lookup Table: statin_ingredient_distribution.csv
Loading Lookup Table: statin_atorvastatin_product_distribution.csv
Loading Lookup Table: statin_ezetimibe_simvastatin_product_distribution.csv

Loading Lookup Table: statin_lovastatin_product_distribution.csv
Loading Lookup Table: statin_pitavastatin_product_distribution.csv
Loading Lookup Table: statin_pravastatin_product_distribution.csv
Loading Lookup Table: statin_rosuvastatin_product_distribution.csv
Loading Lookup Table: statin_simvastatin_product_distribution.csv
Loading submodule modules/medications/strong_opioid_pain_reliever.json
Loading submodule modules/metabolic_syndrome/amputations.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_diagnoses.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_progression.json
Loading submodule modules/metabolic_syndrome/dme_supplies.json
Loading submodule modules/metabolic_syndrome/kidney_conditions.json
Loading submodule modules/metabolic_syndrome/medications.json
Loading submodule modules/snf/skilled_nursing_facility.json
Loading submodule modules/surgery/general_anesthesia.json
Loading submodule modules/total_joint_replacement/functional_status_assessments.json
Loading submodule modules/uti/abx_tx.json

Loading submodule modules/uti/ambulatory_eval.json
Loading submodule modules/uti/ambulatory_path.json
Loading submodule modules/uti/ed_bundle.json
Loading submodule modules/uti/ed_eval.json
Loading submodule modules/uti/ed_path.json
Loading submodule modules/uti/gu_pregnancy_check.json
Loading submodule modules/uti/hpi.json
Loading submodule modules/uti/lab_follow_up.json
Loading submodule modules/uti/labs.json
Loading submodule modules/uti/telemed_path.json
Loading submodule modules/veterans/veteran_suicide_probabilities.json
Loading submodule modules/weight_loss/mend_week.json
Loading module modules/AIS_From_School_Screening_to_SOSORT_Recommendations.json

Loading module modules/acute_myeloid_leukemia.json
Loading Lookup Table: AML.csv
Loading module modules/allergic_rhinitis.json
Loading module modules/allergies.json
Loading module modules/anemia___unknown_etiology.json
Loading module modules/appendicitis.json
Loading module modules/asthma.json
Loading module modules/atopy.json
Loading module modules/atrial_fibrillation.json
Loading module modules/attention_deficit_disorder.json

Loading module modules/bone_marrow_transplant.json
Loading module modules/breast_cancer.json
Loading module modules/bronchitis.json
Loading module modules/cerebral_palsy.json

Loading module modules/chronic_kidney_disease.json
Loading module modules/colorectal_cancer.json
Loading module modules/congestive_heart_failure.json

Loading module modules/contraceptive_maintenance.json
Loading module modules/contraceptives.json
Loading module modules/copd.json
Loading module modules/covid19.json
Loading Lookup Table: covid19_prob.csv
Loading module modules/cystic_fibrosis.json
Loading module modules/dementia.json

Loading module modules/dental_and_oral_examination.json
Loading module modules/dental_encounters.json
Loading module modules/dental_medicare_clustered_encounters.json
Loading module modules/dentures.json
Loading module modules/dermatitis.json
Loading module modules/diabetic_retinopathy_treatment.json
Loading Lookup Table: diabetic_retinopathy_followup.csv

Loading module modules/dialysis.json
Loading module modules/ear_infections.json
Loading module modules/epilepsy.json
Loading module modules/female_reproduction.json
Loading module modules/fibromyalgia.json
Loading module modules/food_allergies.json
Loading module modules/gallstones.json
Loading module modules/gout.json
Loading module modules/hiv_care.json
Loading Lookup Table: hiv_care.csv

Loading module modules/hiv_diagnosis.json
Loading Lookup Table: hiv_mortality_later.csv
Loading Lookup Table: hiv_mortality_early.csv
Loading Lookup Table: hiv_mortality_very_early.csv
Loading Lookup Table: hiv_diagnosis_early.csv
Loading Lookup Table: hiv_diagnosis_later.csv
Loading module modules/home_health_treatment.json
Loading module modules/home_hospice_snf.json
Loading module modules/homelessness.json
Loading module modules/hospice_treatment.json
Loading module modules/hypertension.json
Loading module modules/hypothyroidism.json
Loading module modules/injuries.json

Loading module modules/kidney_transplant.json
Loading module modules/lung_cancer.json
Loading module modules/lupus.json
Loading module modules/mTBI.json
Loading module modules/med_rec.json
Loading module modules/mend_program.json
Loading module modules/metabolic_syndrome_care.json

Loading module modules/metabolic_syndrome_disease.json
Loading module modules/myocardial_infarction.json
Loading module modules/opioid_addiction.json
Loading module modules/osteoarthritis.json
Loading module modules/osteoporosis.json
Loading module modules/pregnancy.json

Loading module modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json
Loading module modules/rheumatoid_arthritis.json
Loading module modules/self_harm.json
Loading module modules/sepsis.json

Loading module modules/sexual_activity.json
Loading module modules/sinusitis.json
Loading module modules/sleep_apnea.json
Loading module modules/sore_throat.json
Loading module modules/spina_bifida.json

Loading module modules/stable_ischemic_heart_disease.json
Loading module modules/stroke.json
Loading module modules/total_joint_replacement.json
Loading module modules/trigger_bone_marrow_transplant.json
Loading module modules/urinary_tract_infections.json
Loading Lookup Table: uti.csv
Loading Lookup Table: uti_recurrence.csv
Loading module modules/veteran.json
Loading module modules/veteran_hyperlipidemia.json
Loading module modules/veteran_lung_cancer.json
Loading module modules/veteran_mdd.json

Loading module modules/veteran_prostate_cancer.json
Loading module modules/veteran_ptsd.json
Loading module modules/veteran_self_harm.json
Loading module modules/veteran_substance_abuse_conditions.json
Loading module modules/veteran_substance_abuse_treatment.json
Loading module modules/vhd_aortic.json
Loading Lookup Table: vhd_as.csv
Loading Lookup Table: vhd_ar.csv
Loading module modules/vhd_mitral.json
Loading Lookup Table: vhd_mr.csv
Loading Lookup Table: vhd_ms.csv
Loading module modules/vhd_pulmonic.json
Loading Lookup Table: vhd_ps.csv
Loading Lookup Table: vhd_pr.csv
Loading module modules/vhd_tricuspid.json

Loading Lookup Table: vhd_tr.csv
Loading Lookup Table: vhd_ts.csv
Loading module modules/wellness_encounters.json
Running with options:
Population: 10
Seed: 42
Provider Seed:43
Reference Time: 1704067200000
Location: Boston, Massachusetts
Min Age: 30
Max Age: 40
Gender: F

1 -- Corie618 Sofia418 Rath779 (40 y/o F) Boston, Massachusetts  (55751)

2 -- Antonia30 Rosa195 Tapia475 (41 y/o F) Boston, Massachusetts  (55585)
3 -- Lola232 Ariadna374 Cardona494 (37 y/o F) Boston, Massachusetts  (50158)

4 -- Esperanza675 María Luisa888 Valverde277 (32 y/o F) Boston, Massachusetts  (45515)
5 -- Jona712 Bonnie873 Rosenbaum794 (35 y/o F) Boston, Massachusetts  (51640)

6 -- Tennille443 Denna536 Nitzsche158 (36 y/o F) Boston, Massachusetts  (49197)
7 -- Ocie984 Bernie827 Homenick806 (40 y/o F) Boston, Massachusetts  (56300)

8 -- Lindsay928 Deja232 Pollich983 (38 y/o F) Boston, Massachusetts  (52138)
9 -- Shondra529 Kyra237 Spinka232 (34 y/o F) Boston, Massachusetts  (46387)

10 -- Chrissy459 Jolynn62 Stanton715 (40 y/o F) Boston, Massachusetts  (58930)

Records: total=10, alive=10, dead=0
RNG=10
Clinician RNG=5638

You've just generated 10 patients! We're happy to know Synthea is helping you with your project.
Like what we're doing? Synthea is an open-source project, and your support helps us keep building.
Please consider ]8;;https://github.com/sponsors/synthetichealthmaking a donation]8;; (https://github.com/sponsors/synthetichealth).

## 4. Every `generate()` argument

This is a **dry-run API example** using `build_argv()`. Snapshot, fixed-record, keep-matching, and custom-module inputs require domain-specific files, so these settings are only used to show argument coverage and inspect the command. Do not pass them to `generate()` until the placeholder files are replaced with valid Synthea inputs.

Passing `None` means that option is omitted and Synthea uses its own default. When both `local_config_path` and `synthea_config` define a property, the mapping is emitted later as a command-line override and therefore wins.

In [9]:
demo_root = artifact_root / "argument_demo"
demo_root.mkdir(parents=True, exist_ok=True)
local_config_path = demo_root / "local.properties"
local_config_path.write_text(
    "generate.only_alive_patients = true\n"
    "exporter.years_of_history = 5\n",
    encoding="utf-8",
)

all_generate_args = {
    "population": 25,
    "seed": 1001,
    "state": "Massachusetts",
    "city": "Boston",
    "clinician_seed": 1002,
    "single_person_seed": 1003,
    "reference_date": "20240101",
    "end_date": "20241231",
    "gender": "F",
    "age_range": "18-65",
    "overflow_population": False,
    "local_config_path": local_config_path,
    "local_modules_dir": demo_root / "modules",
    "initial_population_snapshot_path": demo_root / "initial.snapshot",
    "updated_population_snapshot_path": demo_root / "updated.snapshot",
    "update_time_period": 30,
    "fixed_record_path": demo_root / "fixed_records.json",
    "keep_matching_patients_path": demo_root / "keep_module.json",
    "synthea_config": {
        "generate.thread_pool_size": 1,
        "generate.only_alive_patients": False,
        "exporter.csv.folder_per_run": False,
        "exporter.csv.append_mode": False,
    },
}

declared_args = set(inspect.signature(Synthea.generate).parameters) - {"self", "overwrite"}
assert set(all_generate_args) == declared_args
all_args_argv = synthea.build_argv(Path("java"), Path("synthea.jar"), **all_generate_args)
assert all_args_argv.index("-c") < all_args_argv.index("--generate.only_alive_patients=false")
print(shlex.join(all_args_argv))

java -jar synthea.jar -c /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/local.properties --exporter.baseDirectory=/home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/1aa325cf3d707300d9d6e663cbaca600eaed444a06b7bf49988a6639194cfcf2 --exporter.bfd.export=false --exporter.ccda.export=false --exporter.cdw.export=false --exporter.clinical_note.export=false --exporter.cpcds.export=false --exporter.csv.append_mode=false --exporter.csv.export=true --exporter.csv.folder_per_run=false --exporter.fhir.export=false --exporter.fhir_dstu2.export=false --exporter.fhir_stu3.export=false --exporter.json.export=false --exporter.symptoms.csv.export=false --exporter.symptoms.text.export=false --exporter.text.export=false --generate.only_alive_patients=false --generate.thread_pool_size=1 -s 1001 -cs 1002 -ps 1003 -p 25 -r 20240101 -e 20241231 -g F -a 18-65 -o false -d /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/modules -i /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/initial.snapshot -u /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/updated.snapshot -t 30 -f /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/fixed_records.json -k /home/soham/PyHealth/examples/.artifacts/synthea_csv/argument_demo/keep_module.json Massachusetts Boston

`generate()` argument to Synthea CLI mapping:

| `generate()` argument | Synthea CLI | Meaning |
|---|---|---|
| `seed` | `-s` | Population random seed; random and logged when omitted |
| `clinician_seed` | `-cs` | Clinician generation seed |
| `single_person_seed` | `-ps` | Seed used to reproduce a particular person |
| `population` | `-p` | Requested population size |
| `reference_date` | `-r` | Reference date in `YYYYMMDD` form |
| `end_date` | `-e` | Simulation end date in `YYYYMMDD` form |
| `gender` | `-g` | Restrict generation to `M` or `F` |
| `age_range` | `-a` | Restrict age using `min-max` |
| `overflow_population` | `-o` | Permit extra generated people to satisfy filters |
| `local_config_path` | `-c` | Additional `.properties` configuration file |
| `local_modules_dir` | `-d` | Directory containing custom Synthea modules |
| `initial_population_snapshot_path` | `-i` | Load a previously saved population snapshot |
| `updated_population_snapshot_path` | `-u` | Write the population after an update run |
| `update_time_period` | `-t` | Number of days advanced during a snapshot update |
| `fixed_record_path` | `-f` | Fixed-demographics input used to generate specified people |
| `keep_matching_patients_path` | `-k` | Module used to retain only matching patients |
| `state`, `city` | trailing positional arguments | Geographic generation location |
| `synthea_config` | `--property=value` overrides | Arbitrary supported `synthea.properties` values |
| `overwrite` | wrapper-managed | Rerun Synthea even if output for these settings exists |

Constructor arguments are all wrapper-managed setup:

| Constructor argument | Meaning |
|---|---|
| `output_dir` | Parent of the fingerprinted generation directories |
| `java_path` | Explicit Java executable, otherwise discovered |
| `jar_path` | Explicit Synthea JAR, otherwise the pinned release is used |
| `auto_download` | Allow downloading the pinned JAR when absent |
| `timeout` | Subprocess timeout in seconds for each `generate()` call |

## 5. Load generated CSV through PyHealth

`SyntheaCSVDataset` only reads files: it takes the CSV directory returned by `generate()` plus an optional table selection. Omitting `tables` uses all supported defaults. `dataset_name`, `config_path`, and normal `BaseDataset` keyword arguments such as `cache_dir` and `dev` can also be supplied.

In [10]:
dataset = SyntheaCSVDataset(
    root=csv_path,
    tables=["patients", "encounters", "conditions", "observations"],
    dataset_name="synthea_csv_demo",
    config_path=None,
    cache_dir=artifact_root / "cache",
    dev=False,
)

events = dataset.load_data()
dataset.stats()
# events.head(5)
events

Initializing synthea_csv_demo dataset from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv (dev mode: False)

Using provided cache_dir: /home/soham/PyHealth/examples/.artifacts/synthea_csv/cache/fa318dd5-8d48-5265-84fa-1d581ce4cd9a

Scanning table: patients from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/patients.csv

Scanning table: encounters from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/encounters.csv

Scanning table: conditions from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/conditions.csv

Scanning table: observations from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/observations.csv

No cached event dataframe found. Creating: /home/soham/PyHealth/examples/.artifacts/synthea_csv/cache/fa318dd5-8d48-5265-84fa-1d581ce4cd9a/global_event_df.parquet

Scanning table: patients from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/patients.csv

Scanning table: encounters from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/encounters.csv

Scanning table: conditions from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/conditions.csv

Scanning table: observations from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/observations.csv

Caching event dataframe to /home/soham/PyHealth/examples/.artifacts/synthea_csv/cache/fa318dd5-8d48-5265-84fa-1d581ce4cd9a/global_event_df.parquet...

2026-10-08 18:28:31,163 - distributed.core - ERROR - Exception while handling op terminate
Traceback (most recent call last):
  File "/home/soham/PyHealth/.venv/lib/python3.13/site-packages/distributed/core.py", line 834, in _handle_comm
    result = await result
             ^^^^^^^^^^^^
  File "/home/soham/PyHealth/.venv/lib/python3.13/site-packages/distributed/scheduler.py", line 4367, in close
    self.stop_services()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/soham/PyHealth/.venv/lib/python3.13/site-packages/distributed/node.py", line 79, in stop_services
    application.stop()
    ~~~~~~~~~~~~~~~~^^
  File "/home/soham/PyHealth/.venv/lib/python3.13/site-packages/bokeh/server/tornado.py", line 761, in stop
    raise RuntimeError("Cannot synchronously wait on a running event loop; use 'await stop_async()'")
RuntimeError: Cannot synchronously wait on a running event loop; use 'await stop_async()'

Dataset: synthea_csv_demo
Dev mode: False
Number of patients: 10
Number of events: 2778

Dask DataFrame Structure:
              patient_id event_type       timestamp patients/birthdate patients/deathdate patients/gender patients/race patients/ethnicity patients/marital patients/birthplace patients/city patients/state patients/county patients/zip encounters/id encounters/start encounters/stop encounters/encounterclass encounters/code encounters/description encounters/base_encounter_cost encounters/total_claim_cost encounters/payer_coverage encounters/reasoncode encounters/reasondescription conditions/start conditions/stop conditions/encounter conditions/code conditions/description observations/date observations/encounter observations/code observations/description observations/value observations/units observations/type
npartitions=4
                  string     object  datetime64[ms]             string             string          string        string             string           string              string        string         string          string       string        string           string          string                    string          string                 string                         string                      string                    string                string                       string           string          string               string          string                 string            string                 string            string                   string             string             string            string
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
                     ...        ...             ...                ...                ...             ...           ...                ...              ...                 ...           ...            ...             ...          ...           ...              ...             ...                       ...             ...                    ...                            ...                         ...                       ...                   ...                          ...              ...             ...                  ...             ...                    ...               ...                    ...               ...                      ...                ...                ...               ...
Dask Name: concat, 57 expressions
Expr=Concat(frames=[(RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(861428f), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'birthdate': 'patients/birthdate', 'deathdate': 'patients/deathdate', 'gender': 'patients/gender', 'race': 'patients/race', 'ethnicity': 'patients/ethnicity', 'marital': 'patients/marital', 'birthplace': 'patients/birthplace', 'city': 'patients/city', 'state': 'patients/state', 'county': 'patients/county', 'zip': 'patients/zip'}))[['patient_id', 'event_type', 'timestamp', 'patients/birthdate', 'patients/deathdate', 'patients/gender', 'patients/race', 'patients/ethnicity', 'patients/marital', 'patients/birthplace', 'patients/city', 'patients/state', 'patients/county', 'patients/zip']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(878097d), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'id': 'encounters/id', 'start': 'encounters/start', 'stop': 'encounters/stop', 'encounterclass': 'encounters/encounterclass', 'code': 'encounters/code', 'description': 'encounters/description', 'base_encounter_cost': 'encounters/base_encounter_cost', 'total_claim_cost': 'encounters/total_claim_cost', 'payer_coverage': 'encounters/payer_coverage', 'reasoncode': 'encounters/reasoncode', 'reasondescription': 'encounters/reasondescription'}))[['patient_id', 'event_type', 'timestamp', 'encounters/id', 'encounters/start', 'encounters/stop', 'encounters/encounterclass', 'encounters/code', 'encounters/description', 'encounters/base_encounter_cost', 'encounters/total_claim_cost', 'encounters/payer_coverage', 'encounters/reasoncode', 'encounters/reasondescription']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(3082815), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'start': 'conditions/start', 'stop': 'conditions/stop', 'encounter': 'conditions/encounter', 'code': 'conditions/code', 'description': 'conditions/description'}))[['patient_id', 'event_type', 'timestamp', 'conditions/start', 'conditions/stop', 'conditions/encounter', 'conditions/code', 'conditions/description']], (RenameFrame(frame=Assign(frame=Assign(frame=Assign(frame=RenameFrame(frame=Replace(frame=ReadParquetFSSpec(ba3f9c7), to_replace='', value=<NA>), columns=<method 'lower' of 'str' objects>)))), columns={'date': 'observations/date', 'encounter': 'observations/encounter', 'code': 'observations/code', 'description': 'observations/description', 'value': 'observations/value', 'units': 'observations/units', 'type': 'observations/type'}))[['patient_id', 'event_type', 'timestamp', 'observations/date', 'observations/encounter', 'observations/code', 'observations/description', 'observations/value', 'observations/units', 'observations/type']]], )

In [11]:
patients_table = dataset.load_table("patients")
patient_ids = dataset.unique_patient_ids
patient = dataset.get_patient(patient_ids[0])
patient_events = patient.get_events(return_df=True)

print("Patients:", len(patient_ids))
print("Selected patient:", patient.patient_id)
print("Configured tables:", dataset.tables)
patient_events.head(10)

Scanning table: patients from /home/soham/PyHealth/examples/.artifacts/synthea_csv/generated/3f9629628a6636e7bcd7cdac7b8a158b56c8732ceaa87faf747775c20b85f8e4/csv/patients.csv

Found 10 unique patient IDs

Patients: 10
Selected patient: aee7bbe1-0c45-c028-1e62-1f4cdb30c273
Configured tables: ['patients', 'encounters', 'conditions', 'observations']

shape: (10, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ patient_i ┆ event_typ ┆ timestamp ┆ patients/ ┆ … ┆ observati ┆ observati ┆ observati ┆ observat │
│ d         ┆ e         ┆ ---       ┆ birthdate ┆   ┆ ons/descr ┆ ons/value ┆ ons/units ┆ ions/typ │
│ ---       ┆ ---       ┆ datetime[ ┆ ---       ┆   ┆ iption    ┆ ---       ┆ ---       ┆ e        │
│ str       ┆ str       ┆ ms]       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ aee7bbe1- ┆ patients  ┆ 1985-06-0 ┆ 1985-06-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ condition ┆ 1995-05-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ encounter ┆ 1995-05-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 08:15:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ condition ┆ 2003-07-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ condition ┆ 2003-07-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ encounter ┆ 2003-07-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 06:15:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ condition ┆ 2004-08-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ encounter ┆ 2004-08-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 06:15:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ condition ┆ 2008-07-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aee7bbe1- ┆ encounter ┆ 2008-07-2 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0c45-c028 ┆ s         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1e62-1f4 ┆           ┆ 10:15:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ cdb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6. How Synthea differs from other PyHealth datasets

The event table above has the same shape as every PyHealth dataset: one row per event with `patient_id`, `event_type` (the source table), `timestamp`, and one `<table>/<column>` column per attribute, null for other tables. What differs is the raw input and the codes.

**Raw output.** Synthea wrote the 18 CSV files listed in section 3, each wide and keyed by UUIDs, including billing (`claims`, `claims_transactions`) and institution tables (`organizations`, `providers`, `payers`). `SyntheaCSVDataset` loads the patient-keyed clinical tables by default; `claims` and `claims_transactions` load only when listed in `tables`; institution tables have no patient column and are never loaded.

**Codes.** MIMIC uses ICD-9/10 and NDC. Synthea uses:

| Table | Code system | Example `code` |
|---|---|---|
| `conditions`, `procedures`, `encounters`, `careplans`, `devices`, `supplies` | SNOMED-CT | `714628002` (Prediabetes) |
| `medications` | RxNorm | `849574` (Naproxen sodium 220 MG Oral Tablet) |
| `observations` | LOINC | `4548-4` (Hemoglobin A1c) |
| `immunizations` | CVX | `140` (Influenza, split virus, trivalent, PF) |

So MIMIC tasks such as `MortalityPredictionMIMIC3` and ICD-based `pyhealth.medcode` mappings do not apply; write a Synthea-specific task instead. Every code has a human-readable `description`.

**Other differences.**

- Each patient has a `patients` event at their birth date carrying demographics (`gender`, `race`, `deathdate`, ...).
- There is no separate visit level: clinical events carry an `encounter` UUID; group by it to rebuild visits.
- `observations/value` is a string column holding both numbers and text; `observations/type` says which.
- `conditions` timestamps are dates (midnight); most other tables have full date-times.

On a patient, attributes are accessed without the table prefix:

```python
for event in patient.get_events(event_type="conditions"):
    print(event.timestamp, event.code, event.description)
```